### ISSUE TITLE
Question - unable to encode long URL - Newbie sorry

### ISSUE THREAD

**Issue by SafeCab** [codebude/QRCoder#100]
## Type of issue
Question - Hi I am trying to generate the following QR code which I return as a 512 x 512 jpg.  It works when then number of characters are small but once I have something a little larger it becomes unreadable.

Please can you help me understand how I encode something like the following
hxxp://qr.phonebounce.com/PhoneBounceQR/reader/44_0123456789012345

## Expected Behavior

        var payload = "http://qr.phonebounce.com/PhoneBounceQR/reader/44_0123456789012345";
        QRCodeGenerator qrGenerator = new QRCodeGenerator();
        QRCodeData qrCodeData = qrGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.L);
        QRCode qrCode = new QRCode(qrCodeData);

        ImageConverter converter = new ImageConverter();
        using (Bitmap bitMap = qrCode.GetGraphic(20))

Thanks

Steve

**Comment by codebude** [comment]
Hi @SafeCab ,

what exactly means "unreadable"? You mean your QR code reader can't read it? (If so, which reader (app) and device are you using? Readability stands and falls with the readers camera...)

A possible quick win:
- Do you show the QR code in 100% size (512x512px e.g.) or do you re-scale/downsize it? If you downsize - stop doing it and better lower the size by lowering the pixel per block parameter. E.g.: 
`qrCode.GetGraphic(10)`

For more tips/help - I need more information.

**Comment by codebude** [comment]
Closed due to missing interest of TO.
