### ISSUE TITLE
Javascript / Typescript port

### ISSUE THREAD

**Issue by seveves** [codebude/QRCoder#103]
Hi,
thank you for this library.
I like it so much that I had to port it to a javascript library (at least the basic code generation).

I hope you are ok with that.

You can find the repository [here](https://github.com/seveves/qarrr) and [a live demo](https://codepen.io/seveves/pen/NyNXxv?editors=0010)

Kind regards,
Severin

**Comment by codebude** [comment]
Thanks for letting me know and thanks also for your kind words. Sure, I'm ok with that. If I wouldn't be ok with copying or rewriting the code, I hadn't published it on GitHub nor marked it as MIT licensed. ;-)

But just between us - do you have a little bit too much freetime? It must be a good piece of work to rewrite it... :+1:

**Comment by seveves** [comment]
I wrote the lib with Typescript and it was not that hard to 'translate' to it from C#. The hardest part was dealing with encoding and understanding Linq queries 😑

**Comment by tilkinsc** [comment]
The hardest part was using javascript
