### ISSUE TITLE
using this nuget package in uwp project was refused when submitted to store

### ISSUE THREAD

**Issue by Airborne76** [codebude/QRCoder#104]
I followed the example code to create a QR code in a uwp peoject, then I sumbited to store but was refused by Microsoft.
`Error Found: The supported APIs test detected the following errors:`
`API objc_getClass in libobjc.dylib is not supported for this application type. ZKWeb.System.Drawing.dll calls this API.`
`API objc_msgSend in libobjc.dylib is not supported for this application type. ZKWeb.System.Drawing.dll calls this API.`
`API objc_msgSend_stret in libobjc.dylib is not supported for this application type. ZKWeb.System.Drawing.dll calls this API.`
`API sel_registerName in libobjc.dylib is not supported for this application type. ZKWeb.System.Drawing.dll calls this API.`
`API XCloseDisplay in libx11.dll is not supported for this application type. ZKWeb.System.Drawing.dll calls this API.`
`API XDefaultDepth in libx11.dll is not supported for this application type. ZKWeb.System.Drawing.dll calls this API.`
etc

  I deleted its code just import this nuget package, but it was refused again and showed the same error.

**Comment by codebude** [comment]
Hi @Airborne76 ,

I really don't know how to solve this (other then removing this lib and loosing support for UWP). Maybe @zkweb-framework - the owner of the library can help.

Have you tried to contact him or open an issue at his repo? https://github.com/zkweb-framework/ZKWeb.System.Drawing

**Comment by codebude** [comment]
Hi @Airborne76 ,

I re-checked the current state of the .NET Standard/Core variant of System.Drawing and saw that it's in a usable state now. Back then I used ZKWeb's version because the System.Drawing from the core team wasn't useable for QRCoder. Since it's working now, I replace ZKWeb against the "official" lib. (See commit: https://github.com/codebude/QRCoder/commit/0b347a5963a2510896db0a015aae0e0c99dbade8)

Can you either checkout the code from Github, compile it or use the nightly nuget repo (https://www.myget.org/F/qrcoder/api/v3/index.json) and test if this version is working for the MS check?

**Comment by Airborne76** [comment]
Hi @codebude 
My last submission is still in certification, I will test it in the next submission, it may need few days.

By the way, it passed the local testing after compiled, but can't pass the supported API test in MS' automatic testing, it's really strange🙄

**Comment by codebude** [comment]
I read about such cases where local checks passed and online checks rejected. I think for that case there was a bug on Microsoft side. Nevertheless I exchanged the library now,  because I feel better to went to future with a "more standard"

**Comment by codebude** [comment]
Library with a bigger community. (Damn smartphone. I did not want to close the issue... Just ignore that.)

**Comment by codebude** [comment]
Hi @Airborne76 ,

any news on that topic? Did your last submission pass the certification?

**Comment by Airborne76** [comment]
Hi @codebude ，
I'm still working on the next update, don't worry, I will notice you as soon as it has any result😊

**Comment by codebude** [comment]
Hey @Airborne76 , thanks for the feedback. I'm really sorry, but this error was my fault. I switched the libs, tested locally and then finally forget to change the nuspec-file (used for the automatic build process), too.

So I fixed the dependencies there, too: https://github.com/codebude/QRCoder/commit/b643a1f8d778b6d53bb97567952daaa762977e36
Hopefully this version (1.3.3-CI00007) will work. If so, I can bring this changes up to the official Nuget package.

**Comment by Airborne76** [comment]
Sure @codebude I will test it in my next update, it may need one week if everything goes smoothly😊

**Comment by Airborne76** [comment]
Hi @codebude Good news. It has passed the certification just now. congratulations🤣

**Comment by codebude** [comment]
Nice to hear.  Thanks for the feedback!

**Comment by codebude** [comment]
Hi @Airborne76 unfortunately it took some time (I wanted to collect some more changes, to avoid releasing a new Nuget package every second day), but 30 minutes ago I released [version 1.3.3 on Nuget](https://www.nuget.org/packages/QRCoder/). So this bugfix is now part of the official Nuget package. Feel free to use the Nuget package again.

**Comment by Airborne76** [comment]
Hi @codebude Glad to hear that. It will be a nice kit for developers😊
