### ISSUE TITLE
Table format in QR Code message

### ISSUE THREAD

**Issue by dpjain** [codebude/QRCoder#105]
[Question]
How can we pass an html string as the QR Code text?
I want to display an HTML table in the QRCode.

**Comment by codebude** [comment]
Hi @dpjain ,

I'm not sure if I got you right, but if you meant that you have html in a string, want to encode this string as QR code and want that the user, who scans this QR code, see's the rendered HTML, than this is not the task of QRCoder.

A QR code is something like a "data transport container". It can carry byte/text data. Yes there are things like QR codes which set-up your wifi connection when scanned, but this is the functionalty of the QR code reader app. It's some kind of agreement, that most QR reader apps set-up the wifi network, if the QR code has a special text encoded.

But there is not special agreement/format for HTML. So if you want to encode html in a QR code and want the users see this as HTML you have to write your own QR code reader app, that takes the string from the decoded QR code and shows it inside a html view/browser.

Another option would be, that you don't encode html in the QR code, but load this html to a webserver and just encode the url to the webserver in a QR code. The user then should see a clickable link in the most QR reader apps and can switch to your html-table website with just one click.

**Comment by dpjain** [comment]
Thanks @codebude 
Got your point and will try to give a link which will redirect to the html page.
