### ISSUE TITLE
QR code max string payload, relating to QR code version

### ISSUE THREAD

**Issue by asterixorobelix** [codebude/QRCoder#106]
## Type of issue
Question (e.g. about handling/usage)  
## Expected Behavior
I am trying to find out the potential maximum string payload for a qr code generated with the code from this repo. I see that there are different qr code versions, with different maximum string payloads: [QRCode.com](http://www.qrcode.com/en/about/version.html). What is the default qr code version and is there a way to change the version?

**Comment by codebude** [comment]
QRCoder measures the length of the given payload and chooses automatically the smallest possible version. The potential maximum payload is the same like described here ( http://www.qrcode.com/en/about/version.html ) for version 40.

**Comment by asterixorobelix** [comment]
That is great! Thanks for the fantastic Repo. I assume that the ECCLevel should also be low, in order to reach version 40?

**Comment by codebude** [comment]
The Version describes how much black and white dots a QR has. (And in consequence how much data it can hold.) The ECC level doesn't affect the version. It describes how much percent of the data will be used as redundant backup information.
