### ISSUE TITLE
numeric 5 is converted to percentage

### ISSUE THREAD

**Issue by madhanseeman** [codebude/QRCoder#113]
Dear team,
      when i try to create QR for the following string 

9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl5nj954jtNsjgDJY3xxVeAxl/76E/e66M

i got 

9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl%nj954jtNsjgDJY3xxVeAxl/76E/e66M

kindly help

**Comment by coderabsolute** [comment]
@madhanseeman I have used the `RenderQrCode()` which is under the project `QRCoderDemo` and manage to scan the QRCode with no issues. Can you be more specific to share how and what function you are calling?

**Comment by madhanseeman** [comment]
Dear @coderabsolute ,

i am trying to create Qr code for the following string
9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl5nj954jtNsjgDJY3xxVeAxl/76E/e66M

using the following code from demo

https://www.aspsnippets.com/Articles/Dynamically-generate-and-display-QR-code-Image-in-ASPNet.aspx

 Dim data As String ="9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl5nj954jtNsjgDJY3xxVeAxl/76E/e66M"

              

                Dim qcg As New QRCodeGenerator()
                ' Dim Qc As QRCodeGenerator.QRCode = qcg.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q)
                Dim Qc As QRCodeGenerator.QRCode = qcg.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q)
                Dim bm As System.Drawing.Bitmap = Qc.GetGraphic(20)
                Dim ms As New MemoryStream()
                bm.Save(ms, System.Drawing.Imaging.ImageFormat.Png)
                Dim b As Byte() = ms.ToArray()
                img_2.ImageUrl = "data:image/png;base64," & Convert.ToBase64String(b)

My result of my QR code is  9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl%nj954jtNsjgDJY3xxVeAxl/76E/e66M

**Comment by madhanseeman** [comment]
9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl  5  nj954jtNsjgDJY3xxVeAxl/76E/e66M
9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl  % nj954jtNsjgDJY3xxVeAxl/76E/e66M

**Comment by coderabsolute** [comment]
@madhanseeman I still don't see the issue with the Core Library. The library is doing its job. I have also generated the PNG file, managed to scan without any issues.

**Comment by madhanseeman** [comment]
dear @coderabsolute 

9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl   5    nj954jtNsjgDJY3xxVeAxl/76E/e66M
9LKSpY6DAJpoUPUmWXwKzxBfiCvdLfMl  %    nj954jtNsjgDJY3xxVeAxl/76E/e66M

kindly send your png file.

**Comment by madhanseeman** [comment]
thanks a lot. i will check from my end..

**Comment by codebude** [comment]
Let me guess.  You used the library/dll from the aspsnippets article... They link to an old version with a bug. I already informed them months ago,  but they didn't change the download. Please use the current library version from Nuget as explained in our readme  over here at Github.

**Comment by codebude** [comment]
No problem, you're welcome.
