### ISSUE TITLE
Not working in published site

### ISSUE THREAD

**Issue by madhanseeman** [codebude/QRCoder#115]
Dear team,

    this is the issue i am getting in the published website. but it is working fine in my developing system. 

c:\windows\system32\inetsrv> "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\vbc.exe" /t:library /utf8output /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\36a7a215\2f79f645_dfccd301\pressapi.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DataVisualization\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DataVisualization.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions.Design\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.Design.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\ae8d603b\804ef36c_e517d201\itextsharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Design\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Design.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\30516185\09b7e34f_e4d6d301\App_Code.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\43cdabe0\6bc85450_e4d6d301\QRCoder.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\4fdd0540\805fd65f_e517d201\AjaxControlToolkit.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\433a0913\b8242cb0_e6d6d301\bill.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\61f9d869\bc37d9d3_c8ccd301\Circle.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\67d02bc0\0043c8ad_0ce8d201\Newtonsoft.Json.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\assembly\dl3\87da8498\805fd65f_e517d201\RestSharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /out:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\App_Web_viewimagetestpress.ashx.cdcab7d2.zijvcul5.dll" /D:DEBUG=1 /debug+ /nowarn:41008,40000,40008 /define:_MYTYPE=\"Web\" /imports:Microsoft.VisualBasic,System,System.Collections,System.Collections.Generic,System.Collections.Specialized,System.ComponentModel.DataAnnotations,System.Configuration,System.Linq,System.Text,System.Text.RegularExpressions,System.Web,System.Web.Caching,System.Web.DynamicData,System.Web.SessionState,System.Web.Security,System.Web.Profile,System.Web.UI,System.Web.UI.WebControls,System.Web.UI.WebControls.WebParts,System.Web.UI.HtmlControls,System.Xml.Linq /warnaserror- /optionInfer+  "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\App_Web_viewimagetestpress.ashx.cdcab7d2.zijvcul5.0.vb" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\bill\73401106\1d3fbc45\App_Web_viewimagetestpress.ashx.cdcab7d2.zijvcul5.1.vb"

Microsoft (R) Visual Basic Compiler version 14.7.2053
for Visual Basic 2012
Copyright (c) Microsoft Corporation.  All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to Visual Basic 2012, which is no longer the latest version. For compilers that support newer versions of the Visual Basic programming language, see http://go.microsoft.com/fwlink/?LinkID=533241

C:\inetpub\wwwroot\simbatech.in\bill\viewimageTestpress.ashx(55) : error BC30057: Too many arguments to 'Public Sub New()'.

                Dim qrCode As New QRCode(qrCodeData)
                                         ~~~~~~~~~~ 
C:\inetpub\wwwroot\simbatech.in\bill\viewimageTestpress.ashx(56) : error BC30456: 'GetGraphic' is not a member of 'Qrcode'.

                Using bitMap As System.Drawing.Bitmap = New Bitmap(qrCode.GetGraphic(20, "#006400", "#ffffff", False), New Size(300, 300))

**Comment by codebude** [comment]
- Which version of the QRCoder do you use? 
- From where did you get it (NuGet, self compiled from source, external source/download)?
- Which Framework does your test environment run on? (.NET ...)
- Which Framework does your live environment run on? (.NET ...)
- Can you post the source code which is conflicting?

**Comment by madhanseeman** [comment]
*   Which version of the QRCoder do you use?
 --- 1.3.2 Cl00015

  *   From where did you get it (NuGet, self compiled from source, external source/download)?
Self compiled source from guthub (https://github.com/codebude/QRCoder)
·          Which Framework does your test  environment run on? (.NET ...)
Vs 2017 targetFramework="4.0"  (Developing and testing same machine.)

  *   Which Framework does your live environment run on? (.NET ...)
.net CLR version 4.0  ,windows server 2012 R2


  *   Can you post the source code which is conflicting?
                    My page code..

<%@ WebHandler Language="VB" Class="viewimageTestpress" %>

Imports System.Drawing
Imports System.IO
Imports System.Data
Imports System.Data.SqlClient
Imports QRCoder
Public Class viewimageTestpress : Implements IHttpHandler
    Dim conn As New SqlConnection(ConfigurationManager.ConnectionStrings("Constring").ToString)
    Dim img As Object
    Public Sub ProcessRequest(ByVal context As HttpContext) Implements IHttpHandler.ProcessRequest

        Dim strm As Stream = ShowEmpImage(context.Request.QueryString("enrollmentid"))
        context.Response.ContentType = "image/jpeg"
        context.Response.AddHeader("Content-Disposition", "attachment; filename=IMG" & context.Request.QueryString("enrollmentid"))
        'Dim img As Image = GetImage(context.Request.QueryString("id"))
        'img.Save(context.Response.OutputStream, ImageFormat.Bmp)
        If Not strm Is Nothing Then
            Dim buffer(4096) As Byte
            Dim byteSeq As Int32 = strm.Read(buffer, 0, 4096)
            While byteSeq > 0
                context.Response.OutputStream.Write(buffer, 0, byteSeq)
                byteSeq = strm.Read(buffer, 0, 4096)
            End While
        End If

    End Sub

    Public Function ShowEmpImage(ByVal id As String) As Stream
        Dim ms As MemoryStream = New MemoryStream
        Try


            If conn.State = ConnectionState.Closed Or conn.State = ConnectionState.Broken Then
                conn.Open()
            End If
            Dim cmd As SqlCommand = New SqlCommand("usp_photo_candidate", conn)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.CommandTimeout = 0
            cmd.Parameters.AddWithValue("@enrollmentid", id)
            Dim dr As SqlDataReader = cmd.ExecuteReader
            Dim count As Integer
            Using dt As DataTable = New DataTable()

                dt.Load(dr)
                count = (dt.Rows.Count)
            End Using


            If count > 0 Then
                Dim data As String = tools.Encrypt(id + "##" + DateTime.Now.ToString("ddMMyy"))

                Dim qrGenerator As New QRCodeGenerator()
                Dim qrCodeData As QRCodeData = qrGenerator.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q)
                Dim qrCode As New QRCode(qrCodeData)
                Using bitMap As System.Drawing.Bitmap = New Bitmap(qrCode.GetGraphic(20, "#006400", "#ffffff", False), New Size(300, 300))


                    bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png)
                    Dim byteImage As Byte() = ms.ToArray()
                    ' img_1.ImageUrl = "data:image/png;base64," + Convert.ToBase64String(byteImage)
                    Dim img() As Byte = CType(byteImage, Byte())
                    ms = New MemoryStream(img, False)
                End Using

            End If




        Catch ex As Exception

        Finally
            conn.Close()
        End Try
        Return ms
    End Function
    Public ReadOnly Property IsReusable() As Boolean Implements IHttpHandler.IsReusable
        Get
            Return False
        End Get
    End Property

End Class


Thanks for the response.

**Comment by madhanseeman** [comment]
my site link

http://simbatech.in/bill/viewimageTestpress.ashx?enrollmentid=B180418-MOR-A-046

**Comment by codebude** [comment]
Hm on first sight everything looks fine. Unfortunately I never really have written anything in VB.Net, but used C#. Same goes for ASP. So I'm neither a VB.Net nor an ASP expert, but wasn't there a problem in the earlier days with inherited and/or overloaded constructor methods  from abstract classes in VB.Net? QRCode inherits/uses the constructor from the abstract class AbstractQrCode. Maybe your live environment doesn't like this.

Since you compiled the lib yourself, you could try out the following. Call QRCode-class with the parameterless constructor like `Dim qrCode As New QRCode()` and then pass the qrCodeData manually. (Because that's the only thing the constructor does.) Therefore you should change line 5 of the AbstractQRCode-class from _protected_ to _public_ --> https://github.com/codebude/QRCoder/blob/master/QRCoder/AbstractQRCode.cs#L5 .
Then add the following line right below the initialization of the QRCode object in your code:
`qrCode.QRCodeData = qrCodeData`.

**Comment by madhanseeman** [comment]
thanks man.
now my Visual Studio  is not updating the code. 
while trying to publish the code it shows my old code. 
soon i will fix the issue and update you
