### ISSUE TITLE
Unable to load DLL 'gdiplus'

### ISSUE THREAD

**Issue by xland** [codebude/QRCoder#117]
## Type of issue
Bug  

## Current Behavior
Exception:
Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found
(Exception from HRESULT: 0x8007007E)","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.DrawingCore.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)\n   at System.DrawingCore.GDIPlus..cctor()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233052,"Source":"ZKWeb.System.Drawing","WatsonBuckets":null

**I have these files in my server:**
ZKWeb.System.Drawing.dll
System.Drawing.dll
System.Drawing.Primitives.dll

##  Environment

* Version used:  QRCoder1.3.2
* Compiled from source or NuGet package?:  NuGet package
* Payload/Encoded text:  weixin：//wxpay/s/An4baqw
* Environment: .NETCore, Centos  
* My Code:

> QRCodeGenerator qrGenerator = new QRCodeGenerator();
> QRCodeData qrCodeData = qrGenerator.CreateQrCode(uResult.code_url, QRCodeGenerator.ECCLevel.Q);
> Base64QRCode qrCode = new Base64QRCode(qrCodeData);
> string qrCodeImageAsBase64 = qrCode.GetGraphic(20);

**Comment by codebude** [comment]
Hi @xland ,

this is a known issue. To avoid this error and to have more "standard" code I removed ZKWeb's drawing classes and replaced them with the official System.Drawing in this commit https://github.com/codebude/QRCoder/commit/0b347a5963a2510896db0a015aae0e0c99dbade8

Unfortunately this commit will be become part of the next release, so it isn't covered by the current Nuget package. Thus you have two options:

- Compile the library yourself from source
- Add `https://www.myget.org/F/qrcoder/api/v3/index.json` as source to your Nuget Package Manager and take the QRCoder package from this stream. (This stream contains the latest build. Everytime a commit into this repository is done, this stream will get an update.)

**Comment by codebude** [comment]
Hi @xland ,

nice to hear that the solution worked. So I'll close this issue. Feel free to come back if you have more questions.

**Comment by DucBui93** [comment]
Hi,
I faced this issue although update QRCoder to 1.3.3.
Can you help me to resolve it?
Im using netcore 2.1.
Here is exception:
"Unable to load DLL 'libgdiplus': The specified module could not be found."
This my code - very simple as your example:
var activeLink = EmailConfig.ActiveURl + registerId.ToString();
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(activeLink, QRCodeGenerator.ECCLevel.Q);
            Base64QRCode qrCode = new Base64QRCode(qrCodeData);
            string qrCodeImageAsBase64 = qrCode.GetGraphic(20);
            return qrCodeImageAsBase64;
additional picture:
<img width="1303" alt="screen shot 2018-11-15 at 18 29 21" src="https://user-images.githubusercontent.com/25796214/48547040-b32cd180-e904-11e8-91e8-afd842dd7c67.png">

**Comment by codebude** [comment]
Hi @DucBui93 ,

have you installed the latest libgdi on the system you want to use the QRCoder? Please do the following steps:
```
apt-get install libgdiplus
cd /usr/lib
ln -s libgdiplus.so gdiplus.dll
```
Let me know if it helped.

**Comment by DucBui93** [comment]
> Hi @DucBui93 ,
> 
> have you installed the latest libgdi on the system you want to use the QRCoder? Please do the following steps:
> 
> ```
> apt-get install libgdiplus
> cd /usr/lib
> ln -s libgdiplus.so gdiplus.dll
> ```
> Let me know if it helped.

Thanks,
After install libgdi in my mac.

**Comment by linkjr** [comment]
![_15520305752009](https://user-images.githubusercontent.com/4308856/54014660-6c672e00-41b8-11e9-9672-c50d269e4fed.png)
opps, it's appear again in 1.3.5, and i had installed libgdiplus to linux system.
