### ISSUE TITLE
how to  add custom text on the bottom

### ISSUE THREAD

**Issue by yuzd** [codebude/QRCoder#122]
![_20180511144140](https://user-images.githubusercontent.com/16083659/39910343-7040cc1a-5529-11e8-8695-91f6d8dfb315.png)

**Comment by tilkinsc** [comment]
You'd typically do this yourself.

**Comment by codebude** [comment]
As @tilkinsc mentioned, raus is out of the QR specs. Just draw the text with the usual Graphics class.  For example you could use those code: https://stackoverflow.com/a/32429991
Just pass the QRCode bitmap as myBitmap in the example and adjust the parameters.

**Comment by yuzd** [comment]
thanks
