### ISSUE TITLE
Typo in `OoneTimePasswordAuthAlgorithm`

### ISSUE THREAD

**Issue by AdamWillden** [codebude/QRCoder#123]
I know this is a little late as it'll be a breaking change but I thought I ought to report it if there's any desire to fix it in a new release (if there are any other breaking changes planned).

Note the typo in the enum name `PayloadGenerator.OneTimePassword.OoneTimePasswordAuthAlgorithm`

**Comment by codebude** [comment]
We already discussed about naming changes here: https://github.com/codebude/QRCoder/issues/53 With the outcome that we won't do breaking changes for, now. But if we do, I'll take your request into account.

**Comment by AdamWillden** [comment]
@codebude yep, I had read #53 and thought this would be the outcome however as it was a typo and not just a stylistic change I figured I'd open a separate issue in case any action was to be taken.

Cheers

**Comment by codebude** [comment]
Hi @AdamWillden 
the list in #53 was a proposal for naming changes, but after some discussion we came to the conclusion that the C# naming conventions aren't that clear and that QrCode as also QRCode would be in some way valid by the common convention rules. Since both versions are ok, we decided to postpone this request since we rated some optical sugar lower, than breaking current code --> https://github.com/codebude/QRCoder/issues/53#issuecomment-364452443

Nevertheless, you're right that this one isn't completely about optical sugar, but more a real typo. So I'll fix it in the next release, by writing it correct, but also leave the old name as variant (to not break the code). The old variante with typo will be marked as "obsolete" an stay for a couple of follow-up versions, before complete removal.

**Comment by AdamWillden** [comment]
@codebude Ah yes that'd be a nice way to resolve it....

That said is it possible given that it's the enum that is named wrong and not the property?

The only way I could think to do that is to add a new property for the new type:
```cs
        public class OneTimePassword : Payload
        {
            public OneTimePasswordAuthAlgorithm AuthAlgorithm { get; set; } = OneTimePasswordAuthAlgorithm.SHA1;
            [ObsoleteAttribute($"This property is obsolete, use {nameof(AuthAlgorithm)} instead", false)] 
            public OoneTimePasswordAuthAlgorithm Algorithm 
            {
                get =>AuthAlgorithm .ToObsolete(); // implement extension
                set => AuthAlgorithm  = value.FromObsolete() // implement extension
            };

            [ObsoleteAttribute($"This enum is obsolete, use {nameof(OneTimePasswordAuthAlgorithm)} instead", false)] 
            public enum OoneTimePasswordAuthAlgorithm
            {
                SHA1,
                SHA256,
                SHA512,
            }

            public enum OneTimePasswordAuthAlgorithm
            {
                SHA1,
                SHA256,
                SHA512,
            }
        }
```

**Comment by codebude** [comment]
Hi @AdamWillden ,

I made some slightly changes (added enum casting, shortened ObsoleteAttribute to Obsolete and removed of  *$""*-string in attributes due to [CS0182](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0182)). With this changes it seems to work fine. Any additions?

``` csharp
public OneTimePasswordAuthAlgorithm AuthAlgorithm { get; set; } = OneTimePasswordAuthAlgorithm.SHA1;

[Obsolete("This property is obsolete, use " + nameof(AuthAlgorithm) + " instead", false)]
public OoneTimePasswordAuthAlgorithm Algorithm
{
	get { return (OoneTimePasswordAuthAlgorithm)Enum.Parse(typeof(OoneTimePasswordAuthAlgorithm), AuthAlgorithm.ToString()); }
	set { AuthAlgorithm = (OneTimePasswordAuthAlgorithm)Enum.Parse(typeof(OneTimePasswordAuthAlgorithm), value.ToString()); }
}

public string Issuer { get; set; }
public string Label { get; set; }
public int Digits { get; set; } = 6;
public int? Counter { get; set; } = null;
public int? Period { get; set; } = 30;

public enum OneTimePasswordAuthType
{
	TOTP,
	HOTP,
}

public enum OneTimePasswordAuthAlgorithm
{
	SHA1,
	SHA256,
	SHA512,
}

[Obsolete("This enum is obsolete, use " + nameof(OneTimePasswordAuthAlgorithm) + " instead", false)]
public enum OoneTimePasswordAuthAlgorithm
{
	SHA1,
	SHA256,
	SHA512,
}
```

**Comment by codebude** [comment]
I added this changes over here: https://github.com/codebude/QRCoder/commit/3fbdd5777b6fc116f2854208708bff01db6c9d40

Let me know, if I forgot something - then I'll re-open the issue.

**Comment by AdamWillden** [comment]
@codebude looks great to me
