### ISSUE TITLE
Unresolved reference to Mono.Security when merging assembly

### ISSUE THREAD

**Issue by nitrovent** [codebude/QRCoder#127]
## Type of issue
[ ] Bug  
[x] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior
I wish to use QRCoder in a project that requires strongly named assemblies. 
For this purpose and to reduce the number of dll files we have a project that merges all external references and signs the resulting assembly. 
Merging is done with ILMerge (the resulting assembly contains all the original namespaces). 

## Current Behavior
When trying to merge the assemblies, ILMerge encounters the reference to Mono.Security in the UnityEngine.dll which is unresolved and thus results in an error when merging. 

## Possible Solution (optional)
One possible solution would be for us to fork QRCoder and remove the UnityQRCode functionality (which would also reduce the assembly by ~600kB). 

Another one would be a breaking change for all that use the unity QRCode: splitting the project into two assemblies, one for core functionality without external dependencies and one for extending the rendering, additional payload generators etc. 

Third, finding a solution how to tell ILMerge to ignore the unresolved reference. 
This *kinda* works by adding the Unity as a local reference to the project that merges the assemblies and setting 'copy local' to false. 
But here we're having troubles with our build tasks that we're still evaluating. 

My preference would be the second option ;) 

## Steps to Reproduce (for bugs)
See scenario above

## Your Environment

* Version used:  
* Compiled from source or NuGet package?:  NuGet
* Payload/Encoded text:  -
* Used payload generator:  -
* Used ECC-level:  -
* Used renderer class:  -
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .Net 4.x

**Comment by codebude** [comment]
Hi @nitrovent ,

like in #95 this is already on my todo list. I'll split the library in future. But at the moment I'm still unsure, if I'll:
- Keep QRCoder as it is and build a new "QRCoderLight" package
- If I remove features like Unity from "QRCoder" (thus break functionalty) and create a new "QRCoderHeavy" (with Unity, etc.) package

Currently I prefer the first solution, but I'm still unsure.

**Comment by nitrovent** [comment]
Sounds good.
Maybe extract the core functionality into a "light" or "core" package and reference it in the "full" package which is the current package. so there would be no breaking change upon updating this package and people who are happy with judt the core functionality can switch if they like.

**Comment by codebude** [comment]
Hi @nitrovent,
I removed the UnityQRCode.cs/UnityEngine.dll from the main QRCoder project (see https://github.com/codebude/QRCoder/commit/bfd9205e45dce9e0cc460e8c2e8d8cda383b9d83). From release 1.3.4 on this dependency is gone.

In addition to that I created [QRCoder.Unity](https://github.com/codebude/QRCoder.Unity) which contains only the UnityQRCode.cs + NuGet dependencies to the QRCoder and the UnityEngine. I also updated the readme.md and the [Wiki](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#27-unityqrcode-renderer-in-detail).

I hope this solution fit your needs. Feel free to re-open the issue, if there's anything wrong with this solution or anything you like to discuss about.
