### ISSUE TITLE
Monochrome bitmap

### ISSUE THREAD

**Issue by lellis1936** [codebude/QRCoder#129]
I wish there was a way to create a 1bpp monochrome bitmap, which is so much smaller than 32bpp and 24bpp formats.

**Comment by codebude** [comment]
Currently it's not supported,  but you can just create a normal QRCode with this lib, which returns an C# Bitmap object and then convert this with 3 lines of code as shown here: https://stackoverflow.com/a/17805278

**Comment by lellis1936** [comment]
Thank you, this meets my needs.
