### ISSUE TITLE
Constrain QR size

### ISSUE THREAD

**Issue by lellis1936** [codebude/QRCoder#131]
I would like to constrain my output QR dimension.   I was hoping for a simpler way than this:
```
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(text,QRCodeGenerator.ECCLevel.M);
QRCode qrCode = new QRCode(qrCodeData);

Bitmap bm32bpp;
int pixelsPerModule = 0;
do
{
    ++pixelsPerModule;
    bm32bpp = qrCode.GetGraphic(pixelsPerModule);
} while (bm32bpp.Width < size);

bm32bpp = qrCode.GetGraphic(--pixelsPerModule);
```
Is this the best/only way, or is there some simple calculation I can reliably use instead of this iteration?

Thank you for an elegant and straightforward library.

**Comment by codebude** [comment]
Hi @lellis1936 ,

the *qrCodeData*-object (line 2 in your example code) has a property named *ModuleMatrix*. This contains the information about the white/black blocks of a QRCode.
So just multiply the length of this property (=total amount of QRCode block line) * pixelsPerModule to get the width of the QRCode.

For example:
```csharp
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(text,QRCodeGenerator.ECCLevel.M);
var qrBlocksPerLine = qrCodeData.ModuleMatrix.Count();
//Let's assume qrBlocksPerLine = 10

QRCode qrCode = new QRCode(qrCodeData);

//200x200px QRCoder
var bm32bpp = qrCode.GetGraphic(20);

//320x320px QRCoder
var bm32bpp2 = qrCode.GetGraphic(32);
```

Or in otherwords use this, to calculate pixelsPerModule from target size:
```csharp
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(text,QRCodeGenerator.ECCLevel.M);

//QRCode should be 320px per side at max
double targetSize = 320d;
var ppm = (int)Math.Floor(targetSize/qrCodeData.ModuleMatrix.Count());

QRCode qrCode = new QRCode(qrCodeData);
var bm32bpp = qrCode.GetGraphic(ppm);
```

**Comment by lellis1936** [comment]
Perfect, thank you!   For anyone else who might see this:  since Count is an int, you can also use the slightly simpler:
```
var ppm = targetSize / qrCodeData.ModuleMatrix.Count;
```

**Comment by codebude** [comment]
Hi @lellis1936 ,

one addition to your code. If using:

``` csharp
var ppm = targetSize / qrCodeData.ModuleMatrix.Count;
```
you should either define `targetSize` as `int` or write:

``` csharp
int ppm = targetSize / qrCodeData.ModuleMatrix.Count;
```
otherweise ppm would be of type `double` and the GetGraphics-method needs an int. ;-)

**Comment by lellis1936** [comment]
Ah, yes.   In my code it was int.   What I get for mixing my code with yours.   Good catch.
