### ISSUE TITLE
wkhtmtopdf.exe for asp.net core

### ISSUE THREAD

**Issue by dpjain** [codebude/QRCoder#133]
I have used wkhtmltopdf.exe(version: 0.12.4.0) to convert the html to editable pdf in .net core 1.1

To make the pdf editable, I have added --enable-forms attribute. The input element textbox is successfully converted into pdf editable element, so that we can edit the text box value in the pdf. But the textarea and checkbox are not working. They are editable, but not able to save the checkbox value and also not able to pre-populate the textarea value.

Any idea about the same issue.

**Comment by codebude** [comment]
I think this issue was posted in the wrong repository since QRCoder doesn't use wkhtml. Did you want to post in the Wordpress2Doc repository?
