### ISSUE TITLE
VCard support for Photo?

### ISSUE THREAD

**Issue by knavet** [codebude/QRCoder#134]
## Type of issue
[ ] Bug  
[x] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Question
Does QRCode for VCard (v3) feature supports contact's photo?
Tried using Base64 and URL method, both not detectable.

eg
PHOTO;TYPE=JPEG;VALUE=URI:https://xxxx
END:VCARD

or

PHOTO;TYPE=JPEG;ENCODING=b:[insert Base64 string of image here]
END:VCARD

## Your Environment
* Version used:  Latest
* Compiled from source or NuGet package?:  Nuget
* Payload/Encoded text:  
* Used payload generator:  QRCode
* Used ECC-level:  L, M
* Used renderer class:  
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  4.X
-->

**Comment by Ruffio** [comment]
@knavet can this issue be closed?

**Comment by knavet** [comment]
Yes pls thx

**Comment by sgkalyans** [comment]
I tried the above  mentioned but no profile picture shown when I can the QR code. I'm urgently looking for this. Please help.
