### ISSUE TITLE
BitmapByteQRCode.HexColorToByteArray swaps R and B in RGB colors

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [codebude/QRCoder#139]
## Type of issue
[x] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
`BitmapByteQRCode.GetGraphic(20, "#ff0000", "#ffffff")` should generate a red graphic, just like `BitmapByteQRCode.GetGraphic(20, new byte[] { 0xff, 0x00, 0x00 }, new byte[] { 0xff, 0xff, 0xff })`.

## Current Behavior
The graphic is generated as blue (`#0000ff`).

## Possible Solution (optional)
Change https://github.com/codebude/QRCoder/blob/master/QRCoder/BitmapByteQRCode.cs line 85 to set `byteColor[i]` instead of `byteColor[2-i]`

## Steps to Reproduce (for bugs)
```

        private IActionResult GetPlainQRCode(string url)
        {
            PayloadGenerator.Url generator = new PayloadGenerator.Url(url);
            string payload = generator.ToString();

            using (var qrGenerator = new QRCodeGenerator())
            {
                using (var qrCodeData = qrGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q))
                {
                    using (var qrCode = new BitmapByteQRCode(qrCodeData))
                    {
                        var qrCodeAsByteArray = qrCode.GetGraphic(20, "#FF0000", "#FFFFFF");
                        return File(qrCodeAsByteArray, "image/bmp");
                    }
                }
            }
        }
```

## Your Environment

* Version used:  1.3.3 (it looks like 1.3.4 was set in April but has not been released on nuget, is that right?)
* Compiled from source or NuGet package?:  Nuget
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .NET Core 2.1

**Comment by codebude** [comment]
Fixed in https://github.com/codebude/QRCoder/pull/148
