### ISSUE TITLE
Icon in TOTP apps

### ISSUE THREAD

**Issue by sargola** [codebude/QRCoder#140]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior
I would like to be able to specify an image for the apps that scan the QRCode and calculate the codes. LastPass has its own icon and Microsoft accounts even have their avatar in it.

## Current Behavior
I am not able to so this as far as I can see.

* Version used:  1.3.3
* Compiled from source or NuGet package?:  nuget
* Payload/Encoded text:  
* Used payload generator:  OneTimePassword
* Used ECC-level:  Q
* Used renderer class:  QRCodeData
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):   .net 4.x
-->

**Comment by sargola** [comment]
one remark: I found the overlaod of qrCode.GetGraphic(...) which takes a Bitmap but it just renders the image in the center, the qrcode is still scannable but does not show an icon in the microsoft or google authenticator app. Thanks for your support!

**Comment by sargola** [comment]
heya, any news on this?
cheers,
Michi

**Comment by codebude** [comment]
Hi @sargola ,

I'm not sure if I got your request, but are you asking for a visible icon on the QR code image or are you asking for a image, which shows up in the authenticator apps when the QR code is scanned?

If first, then you should use the GetGraphic overload which takes an Bitmap. The one you already found. If you want the second, then I have to disappoint you. Im pretty sure LastPass and Microsoft doesn't save any image information in the QR codes, but the authenticator apps display the images based on the issuer information from the QR codes. I think, when the authenticator app scans a code from Microsoft it has some logic to show Microsoft's logo. So if you want your logo to show up, then you should get in contact with the different authenticator app providers.

For example I decoded an TOTP qr code from last pass.
![lpass](https://user-images.githubusercontent.com/2236234/46742427-4be98500-cca7-11e8-9c23-ae491dc71a13.png)

Its content looks like this:
```
otpauth://totp/LogMeIn%20Accounts%3A%20scott%40lastpass.com?secret=PO25V3FOQZYZDIKVUHV2EJXLFC4V3LSR&issuer=LastPass&lmirequesttoken=01_W1FmfRVcinNiLYUvnqvhpbms9qXIswP8r8fHH3vO9CoUI7RsZ8oFb3RnT2JPaZ2A&lmiversion=1
```

This url clearly hasn't any image information in it. If your authenticator app shows a lastpass logo nevertheless, then it's part of the authenticator's source code.

**Comment by sargola** [comment]
Hi Raffael,  

I am looking for your second scenario and was already fearing that there is some magic included in the apps itself and not in the QR code. Thanks for coming back and answering!  

cheers,  
Michi
  

Michael Seirer Consulting  
m: +43 699 15083777(tel://+43%20699%2015083777)  
w: https://www.seirer.net(https://www.seirer.net/)
a: Reithofferplatz 12/17 1150 Wien / Österreich .
