### ISSUE TITLE
Usage in Unity3d

### ISSUE THREAD

**Issue by CarlosMassiah** [codebude/QRCoder#142]
What is the installation method for Unity3D?

Importing the code into Unity does not work.
The "UnityEngine.dll" clashes with the Unity's own dll. 
The QRCoder code uses C# 6.0 calls while Unity is Mono 3.5 or 4.x.

**Comment by codebude** [comment]
Hi @CarlosMassiah ,

C# 6.0 should be possible. See last answer over here: https://answers.unity.com/questions/1123341/can-unity-work-with-c-60-code-and-how.html
In addition to that, Unity-support was removed from this package and rebuild in an own package. Please have a look over here: https://github.com/codebude/QRCoder.Unity

**Comment by codebude** [comment]
Hi @CarlosMassiah ,

I did some tests and created a demos on Linux (Ubuntu) and Windows (10). Both worked fine.

Check the quick instructions here: https://github.com/codebude/QRCoder.Unity/blob/master/README.md
And the demo project here: https://github.com/codebude/QRCoder.Unity/tree/master/QRCoder.Unity.Demo
