### ISSUE TITLE
Is it possible to force QR code type to text instead of URI?

### ISSUE THREAD

**Issue by Floppe** [codebude/QRCoder#144]
## Type of issue
[ ] Bug  
[X ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Plain text when scanned.
QR encoding "https://website.com/" should show only the text, not open the URL.

## Current Behavior
Type is URI, so Android tries to open URL.

**Comment by codebude** [comment]
This is nothing which is handled by QRCoder.  When you enter an URL as text, it is encoded as text.  When readers open the URL instantly in a browser than this is done in the code of the reader app.  A lot of readers open URLs directly when they see that there's only a URL in a QRCode. 

Proof: try to read out the generated QR code with a web-based QR code reader in your browser. You will see that it contains no commands,  just the plain URL.  

Workaround: If you want to ensure that readers don't open the link immediately,  prefix your URL like: "Url: http://myserver.com"

**Comment by Floppe** [comment]
Oh. I wonder then how for example http://goqr.me/ does handle this. I've used this service to create texts which starts with URLs. And no prefix used.

**Comment by codebude** [comment]
An their codes, scanned with *the same* reader app,  doesn't launch the webbrowser?  If so, could you please post two examples codes.  One from the mentioned generator and one from QRCoder you generated? I would like to debug and compare them.

**Comment by Floppe** [comment]
Yes, My bad. I'm sorry. There were a linefeed and a suffix which I missed when the payload was URL encoded. Decoded and the results are the same when scanning the codes.

**Comment by codebude** [comment]
No problem.  You're welcome.  :-)
