### ISSUE TITLE
1.3.4 for .net 4.0

### ISSUE THREAD

**Issue by BlackZork** [codebude/QRCoder#154]
I just tried to upgrade from 1.3.3 to 1.3.4 and VS warns about incompatible versions:

Warning		The primary reference "QRCoder, Version=1.3.4.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".

Downgrading to 1.3.3 removes this warning.

(My app still needs to support WinXP, so I cannot use .net 4.5)

**Comment by codebude** [comment]
Hi @BlackZork ,

thanks for the feedback. This change came with this commit https://github.com/codebude/QRCoder/commit/8f98caef6e7c436d98305065dd24d86e7cef9747#diff-6adc18d6504da52c22fbd4da68d973ee which was part of one of the merge requests. I'll try to change it back to 4.0. If it recompiles without errors, I'll publish a new version within the next hours.

**Comment by codebude** [comment]
Fixed package was published: https://www.nuget.org/packages/QRCoder/1.3.5 
(It may take ~30 minutes until it is fully indexed by NuGet and available via package manager.)

Please let me know, if this solved your problem.
