### ISSUE TITLE
Memory managment

### ISSUE THREAD

**Issue by abdoutech93** [codebude/QRCoder#16]
I'm using QRCoder in an application and i must generate code for ticket (the number is very important and bigger) and i get an exception of out of memory and i guest the problem is in qrcode generation, now i need to implement IDisposable interface. 
i'd need to know if i'm in good way to fix it and if my troublshoot is right ?

**Comment by abdoutech93** [comment]
![after](https://cloud.githubusercontent.com/assets/16762124/13586031/000cd8a8-e4bf-11e5-9feb-65bbe2ad172e.JPG)
the first picture is a graphic of values of allocated memory after implementation of disposable methodes, and the second picture is a screenshot of memory allocation before implementation of disposable methodes.
![before](https://cloud.githubusercontent.com/assets/16762124/13586029/ffed1888-e4be-11e5-80e3-0982c43cf8de.JPG)

**Comment by codebude** [comment]
Hi @abdoutech93 - it seems you've already implemented the disposable code. Would you be so kind and share your code changes with us by opening a pull request?

**Comment by abdoutech93** [comment]
Yes, of course. 
i'll share it

**Comment by codebude** [comment]
Merged your pull request. So this issue can be close.
