### ISSUE TITLE
QRCode.GetGraphic generate QrCode error，use QRCoderDemo project

### ISSUE THREAD

**Issue by lovefather** [codebude/QRCoder#160]
when render a logo/image of the QR code set `lightColor=Color.Transparent `
like this:
![image](https://user-images.githubusercontent.com/5752488/50725067-d3258800-1132-11e9-922c-bd06f8e91f92.png)

**Comment by hisenberg1** [comment]
It appears that the opacity is being applied at the logo layer. It works correctly when there is no logo.

**Comment by codebude** [comment]
Fixed in https://github.com/codebude/QRCoder/commit/7507ab63b4fe90c833863f3e9561a993aa891a04
