### ISSUE TITLE
WIFI Authentication

### ISSUE THREAD

**Issue by michelelondon** [codebude/QRCoder#164]
Hello, i have downloaded  the solution as i was interesting in generate Qrcode for Wifi.
What i have noticed is that the enum PayloadGenerator.WiFi.Authentication only has WEP and WAP; no WAP2.

**Comment by codebude** [comment]
The WPA flag supports both WPA and WPA2. Try it out and let me know if this solved your question.

**Comment by codebude** [comment]
No feedback --> closed
