### ISSUE TITLE
QR code output as Vector Image

### ISSUE THREAD

**Issue by aniltc-rails** [codebude/QRCoder#167]
## Type of issue

is it possible to create output as vector image  ?

## Expected Behavior
Vector Image

**Comment by codebude** [comment]
Hi @aniltc-rails ,

yes, it is possible. Please check the documentation/wiki. You have to use the SVG-rendering class. Example can be found in the wiki: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#26-svgqrcode-renderer-in-detail
