### ISSUE TITLE
Unity3D System.Drawing.Common.dll

### ISSUE THREAD

**Issue by DogukanErdem** [codebude/QRCoder#168]
Hi, trying to implement UnityQRCoder for my project, but I'm having an issue.

-First I got this error : Unable to resolve reference 'System.Drawing.Common'. Is the assembly missing or incompatible with the current platform?

-Then I added System.Drawing.Common.dll to my Project Tree

-After that I got this error: Unloading broken assembly Assets/Packages/QRCoder.1.3.4/lib/net35/QRCoder.dll, this assembly can cause crashes in the runtime

Environment:
Unity3D 2018.3.2f1  
Compiled from: QRCoderUnity(NuGet) / QRCoder(Compiled from script)
Environment .NET 4.x

**Comment by codebude** [comment]
Hi @DogukanErdem ,

please install the Unity version via the Nuget package manager for Unity as described here: https://github.com/codebude/QRCoder.Unity

If you still get an error, please open an issue here: https://github.com/codebude/QRCoder.Unity/issues
