### ISSUE TITLE
Is it possible to specify the cell size in millimeters?

### ISSUE THREAD

**Issue by yuya-tani** [codebude/QRCoder#171]
Hi.
I am a person using QRCoder.
I am always grateful for your help.

When I create a QR code (CreateQrCode), I think that the size of the cell is a point,
Is there a way to specify in millimeters?

**Comment by codebude** [comment]
What do you mean by cell size? Do you mean the black and white modules? If so, try tinder the pixelsPerModule parameter of the rendering method.

**Comment by yuya-tani** [comment]
Thank you for reply.
And I'm sorry I didn't tag it

Convert from mm to point before passing to pixelsPerModule
I will try by passing method.
I apologize to you for a fuss over.

**Comment by codebude** [comment]
Hi @yuya-tani mm may change with the screen's or printer's DPI. Keep that in mind.
