### ISSUE TITLE
Is it possible to create a GS1 QR code?

### ISSUE THREAD

**Issue by yuya-tani** [codebude/QRCoder#172]
The specifications are slightly different from the normal QR code
I think there is a QR code for GS1, but is it possible to create that GS1 QR code?

**Comment by codebude** [comment]
@yuya-tani do you have a documentation/link/article about the (technical) differences between regular QR code and GS1 QR code? I tried to find out what's going on, but by reading multiple articles from GS1 it's still unclear to me, if a GS1 QR code is a regular QR code with just a specific payload/content or if it's (in addition) has also changed the technical part/encoding.

**Comment by yuya-tani** [comment]
@codebude 
I'm sorry. I can not convey accurate information because I do not know the detailed specifications.

It looks like it is written in detail in "Page 11 of 15" of the following PDF.
https://www.gs1us.org/DesktopModules/Bring2mind/DMX/Download.aspx?Command=Core_Download&EntryId=169

After, I am sorry in the Japanese site, but to the following site.
http://www.dsri.jp/standard/2d-symbol/gs1-qr.html#symbol
The same thing as above "FNC 1",
The "Note 2" seems to have specifications such as not expressing parenthesis part of application identifier.

If it does not correspond to the GS1 QR code, that is no problem at all.
Best Regard.

**Comment by codebude** [comment]
The above linked paper only talks about the content/payload which should be encoded in a GS1 QR code. Unfortunately it doesn't talk about technical details. So for now I assume that QRCoder isn't able to create valid GS1 codes. 

Feel free to create a feature request (new issues) if you have detailed information about how to implement a GS1 QR code. (Or even better - implement it and then send in a merge request.)
