### ISSUE TITLE
Circle QRCode generation

### ISSUE THREAD

**Issue by Sopheakmorm** [codebude/QRCoder#173]
## Image Generation
I want to display generated QRCode image with bootstrap circle. but when I try to put it in circle wrapper of bootstrap the scanner unable to read.

Can we make the output image as circle frame like `https://i.pinimg.com/564x/8a/a0/05/8aa00528c91b6443d59ad55daa130e98.jpg`

Thank you

**Comment by codebude** [comment]
Hi @Sopheakmorm ,

currently there is no rendering class, which creates round QR code graphics. But feel free to write your own renderer. Therefore have a look at the QRCode class (https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCode.cs) as also at the AbstractQrCode class (https://github.com/codebude/QRCoder/blob/master/QRCoder/AbstractQRCode.cs). As you can see all renderers work with the abstract class. So create a new class like "RoundQRCode.cs" which implements AbstractQRCode and write the rendering logic to draw a round QRCode. Additional information can be found here: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers

If you don't want to write your own class, you can try to take the QRCode graphic, and draw a white border around it via Graphics class from .NET framework. Thus the circle class of Bootstrap should only cut off the white space and not the QRCode itself, which should keep the code readable as a result.

**Comment by Sopheakmorm** [comment]
Hi @codebude,
I will create `RouldQRCode.cs` implementation and then make pull request with you.
Thank you anyway.

**Comment by bugnuker** [comment]
@Sopheakmorm did you have any luck making the round render?

**Comment by Sopheakmorm** [comment]
Hi @bugnuker. It's success.

**Comment by mikewcameron** [comment]
@Sopheakmorm do you have any example of your results? I don't intend to see what you wrote (unless you want to share) but rather your results while extending qrcoder.

**Comment by codebude** [comment]
Hi @mikewcameron ,

never got a PR from @Sopheakmorm, but meanwhile @nigelthorne setup the ArtQRCode, which was embedded and overhauled just last week. So you might want to have a look...
- [ArtQRCode wiki (how to use)](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#211-artqrcode-renderer-in-detail)
- [CI-build package](https://github.com/codebude/QRCoder/packages/1072246)

The ArtQRCode will be part of the next official QRCoder release (1.4.2). If you want to test it right now, either checkout the Github repository and compile it yourself or simply use the GithubPackages CI-package linked above. (If you need help with GithubPackages, check [this wiki section](https://github.com/codebude/QRCoder/wiki/How-to-use-QRCoder#22-latestnightly-builds) and the blog post linked there.)

**Comment by Sopheakmorm** [comment]
Hi @mikewcameron, it was long time ago. let me find it first.

**Comment by NigelThorne** [comment]
The round codes are just the square codes with some extra stuff around the edges and circles used for the corners.  I like the "merge the dots into lines" look about it.
