### ISSUE TITLE
QRCode is missing

### ISSUE THREAD

**Issue by lailaberiou** [codebude/QRCoder#174]
## Type of issue
- [ ] Bug  
- [x] Question (e.g. about handling/usage)  
- [ ] Request for new feature/improvement  

## Expected Behavior
It isn't supposed to give an error

## Your Environment
* Visual Studio 2017
* Universal Windows Application
<a href="https://www.noelshack.com/2019-15-3-1554905774-pb-qrcode.png"><img src="https://image.noelshack.com/minis/2019/15/3/1554905774-pb-qrcode.png" border="0" alt="1554905774-pb-qrcode.png - envoi d'image avec NoelShack" title="1554905774-pb-qrcode.png"/></a>

**Comment by codebude** [comment]
The QRCode renderer relies on classes which aren't available in the UWP environment. Please check the compatibility table in our wiki: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#2-overview-of-the-different-renderers

Use on of the renderers which aren't supported on "full .net framework" only. You'll find example code for alle renderers in the wiki also.

**Comment by thisisclint21** [comment]
So please update README :)

**Comment by ngnam** [comment]
yes. i must use version qrcoder 1.4.1 with fix miss namespace qrcode

**Comment by valdrodrigues** [comment]
> The current stable version (1.4.3) has the error. I mean "QRCode" is missing. However, the previous version (1.4.2) has it. That's the one I used. The error needs to ne fixed on the current version.

Yes, i had the same error and your solution worked for me. Thanks.
