### ISSUE TITLE
need QR code decoder C# code

### ISSUE THREAD

**Issue by sathishsiri1985** [codebude/QRCoder#175]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
Hi @sathishsiri1985 ,

QRCoder is just a generator. It's not planned to integrate an encoder funtionality as discussed here: https://github.com/codebude/QRCoder/issues/71 Nevertheless, if you want to contribute and write the decoding funtionality, feel free to do so and send in a merge request afterwards. ;-)

For now, you should try ZXing.NET for QRCode decoding:
https://github.com/micjahn/ZXing.Net
