### ISSUE TITLE
Generating Hex String QR Code 

### ISSUE THREAD

**Issue by chungyau97** [codebude/QRCoder#180]
Value = 22fd30df7c13fb69f7f87e3a8728f0daf6ab360b82ec9e6d8c1157e19add4013080b3399eff31644e24553e9c30b697078492d9da33bf0a9235ab87a7662398a06c782a31acfc79c5023344b11f3750bb98e500b01

 ECC-Level = M 

Based on your coding, 
Hex String - > ByteArray ->utf7 -> ISO-8859-1 -> foreach(var b in codeBytes) 
The last value will be binary string.
Then use the last value to create QR Code

But when I scan the QR code it's in ISO-8859-1. How to achieve it to generate ISO-8859-1 as result?

**Comment by codebude** [comment]
Sorry, but I can't follow you.

> But when I scan the QR code it's in ISO-8859-1. How to achieve it to generate ISO-8859-1 as result?

You say when read it gives you ISO-8859-1 and then you ask what to do, to get ISO-8859-1. Seems like there is no problem?!

Could you please clarify, what you want to archive? (Maybe explain the whole picture/concept of what you want to archive.)
