### ISSUE TITLE
Crashes when data is too long, could be a specific exception to be easily catched

### ISSUE THREAD

**Issue by Pol63** [codebude/QRCoder#181]
When data is too long to be encoded it simply crashes

You should create an DataTooLongException and in QrCodeGenerator.GetVersion you should get the version list in a field, test the count, if empty throw the exception else return the .Min
(and add xml at the public methods to specify it can throw this exception)

Sorry i'm new to GitHub, dunno how to create a pull request … need to fork maybe ...

**Comment by ManticSic** [comment]
Do I assume rightly that this mean that only a Exception is throwen if the max length of a qr code is exceeded (> 3kb) instead of e. g. DataTooLongException?

Or does it mean that application always crashes if u pass a string which is longer the defined max size?

**Comment by Pol63** [comment]
it crashes because the IEnumerable is empty and the code do .Min(…)

**Comment by codebude** [comment]
Added DataTooLongException incl. dynamic error text and XML comments in https://github.com/codebude/QRCoder/commit/da89291a6646c0be046382646e184bac08e48e84
