### ISSUE TITLE
Swiss QR Code according to Swiss Payment Standards Version 2.0

### ISSUE THREAD

**Issue by sensorflo** [codebude/QRCoder#184]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[X] Request for new feature/improvement  

## Expected Behavior

Currently, SwissQrCode implements version 1.0 of the Swiss Payment Standards. Are there any plans for implementing version 2.0? See https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf.

**Comment by sensorflo** [comment]
Thanks a lot. I also could start working on it, starting about next week. I found the following document which lists the differences between version 1.0 and version 2.0: https://www.paymentstandards.ch/dam/downloads/change-documentation-qrr-de.pdf.

**Comment by codebude** [comment]
Hi @sensorflo ,

did you already start implementing the changes? Otherwise I'll do so this evening.

**Comment by codebude** [comment]
Payload generator was updated to version 2.0 in this commit https://github.com/codebude/QRCoder/commit/bbba9cba4961ea96d9053c1c60f5480e844548bb .
A new Nuget package will be released this evening.
