### ISSUE TITLE
Nuspec out of date? (System.Drawing.Common)

### ISSUE THREAD

**Issue by AdamWillden** [codebude/QRCoder#190]
May be experiencing a bug, or maybe not. Either way I've noticed a version mismatch you may want to get in sync:

https://github.com/codebude/QRCoder/search?q=system.drawing.common&unscoped_q=system.drawing.common

![image](https://user-images.githubusercontent.com/4629144/60604355-6de3e400-9daf-11e9-8428-62db991656d8.png)

The issue I'm being presented with is this:

`Assembly 'QRCoder' with identity 'QRCoder, Version=1.3.6.0, Culture=neutral, PublicKeyToken=null' uses 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Drawing.Common' with identity 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

I'm not using system drawing common anywhere in my project (a .Net Core 2.2 web project).

**Comment by AdamWillden** [comment]
Think it is something you need to resolve. As soon as I add in `System.Drawing.Common@4.5.1` the issue goes away.

**Comment by thomaslevesque** [comment]
This really needs to be fixed. It causes a build warning if you also reference the stable `System.Drawing.Common`:

> Warning	MSB3277	Found conflicts between different versions of "System.Drawing.Common" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

**Comment by flookami** [comment]
Same issue for me : _**error CS1705: Assembly 'QRCoder' with identity 'QRCoder, Version=1.3.6.0, Culture=neutral, PublicKeyToken=null' uses 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Drawing.Common' with identity 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'**_

Any plan to merge fix soon ? #192

**Comment by andrejpanjan** [comment]
Is there a workaround?

**Comment by deleteLater** [comment]
The same issue, then i use QRCoderNetCore as a temp solution.

**Comment by deleteLater** [comment]
Install the latest System.Drawing.Common as a temp solution works for me.

**Comment by codebude** [comment]
Should be solved with this commit: https://github.com/codebude/QRCoder/commit/d428ce5f504ec8b4f689ea87d86599301b2993d2
