### ISSUE TITLE
request / bug with url pre-appending http://

### ISSUE THREAD

**Issue by daninmanchester** [codebude/QRCoder#196]
I'm trying to use the QR code to deep link in to an app.
The problem is that it appends http:// and so breaks my custom app link.

myApp://method/create?sessionKey=z9o4BP

becomes 

http://myApp://method/create?sessionKey=z9o4BP

and clearly this does not work.

Being able to disable this behaviour would be useful.

**Comment by codebude** [comment]
Hi @daninmanchester ,

this is not a bug. You used the PayloadGenerator for "urls". The task of this generator is to create valid weblinks. All of the PayloadGenerators have a special purpose like this, but they're all just creating a specially formatted string.

If you want to encode your string just as it is, you don't have to use a PayloadGenerator, but can simply pass the string to the QRCoder. Then nothing will be appended or prefixed.

```Csharp
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("myApp://method/create?sessionKey=z9o4BP", QRCodeGenerator.ECCLevel.Q);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(20);
```
