### ISSUE TITLE
Add field to vCard generator - ease ?

### ISSUE THREAD

**Issue by jWinnaar** [codebude/QRCoder#197]
How difficult/easy is it to add more fields to vCard generator?

**Comment by tijana-vujanac** [comment]
I just did it with a help of https://en.wikipedia.org/wiki/VCard
For vCard 3.0

For what I need of course.
I don't have time to contribute at the moment, but when I do, will definitely add it if it is possible.
```

string payload = string.Format("BEGIN:VCARD\r\nVERSION:3.0\r\nN:{0};{1};;;\r\nFN:{1} {0}\r\nTEL;TYPE=HOME,CELL:{2}\r\nTEL;TYPE=WORK,VOICE:{3}\r\nADR;TYPE=HOME,PREF:;;{4} ;{5};;{6};\r\nURL:{7}\r\nEMAIL:{8}\r\nORG:{9}\r\nTITLE:{10}\r\nADR;TYPE=WORK,PREF:;;{11}; {12};;{13};\r\nEND:VCARD",
 lastName, firstName, mobile, workphone, homeAddress, homeCity, homeZip, url, email, company, title, workAddress, workCity, workZip);
```

**Comment by codebude** [comment]
The question was if it is easy. The answer is yes. So I'll close this issue. If you want specific fields added, please raise a new issue and name the fields that shall be added. :-)
