### ISSUE TITLE
Could not resolve type with token 0100002b from typeref

### ISSUE THREAD

**Issue by ghbarr** [codebude/QRCoder#199]
## Type of issue
[ ] Bug  
[X] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
I am using the 5 lines of code to generate the barcode, I have imported both System.Drawing and QRCoder libraries.

```
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(encodeData, QRCodeGenerator.ECCLevel.Q);
QRCode qrCode = new QRCode(qrCodeData);   //error occurs on this line
Bitmap qrCodeImage = qrCode.GetGraphic(20);
```

I would expect a QR Code to be generated

## Current Behavior
System.TypeLoadException: 'Could not resolve type with token 0100002b from typeref (expected class 'QRCoder.QRCode' in assembly 'QRCoder, Version=1.3.6.0, Culture=neutral, PublicKeyToken=null')'

## Your Environment

* Version used:  1.3.6
* Compiled from source or NuGet package?:  NuGet Package
* Payload/Encoded text:  "Description" (text field on xamarin forms)
* Used payload generator:  QRCodeGenerator.CreateQrCode
* Used ECC-level:  Q
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  Xamarin Forms .NETStandard 2.0

**Comment by almirvuk** [comment]
Same exception on Xamarin.Forms as well Xamarin.Forms with .NETStandard 2.0
