### ISSUE TITLE
QRCoder 1.3.6 on NuGet does not have strong name (signed)

### ISSUE THREAD

**Issue by gdalsnes** [codebude/QRCoder#200]
Our app(s) have strong name and then all assemblies used must have strong name signature.
Can you add this?

**Comment by gdalsnes** [comment]
I got around it by using https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/ and signing with a .snk I generated myself (strong name key). Would be nice to not have to do this for new versions:-)

To sign it on your end I think you generate your own .snk file that you specify during compilation. I think this .snk file should not be public.

**Comment by TimzChen** [comment]
You can see the author reply at this link: https://github.com/codebude/QRCoder/issues?q=is%3Aissue+is%3Aclosed+signed
