### ISSUE TITLE
Generated double parameters

### ISSUE THREAD

**Issue by ogousseau** [codebude/QRCoder#206]
Hi,

Thanks for this library,
Want i generate QRCode with it for un URL, the QRCode contains 2x param of URL.

For exemple :
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("https://myurl.com?id=1", RCodeGenerator.ECCLevel.Q);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(20);

Give a QR Code with https://myurl.com?id=1&id=1

Strange no ?

Bonne soirée.
Olivier

**Comment by codebude** [comment]
Can't reproduce the error. If this still occurs, please provide a sample QR code image.
