### ISSUE TITLE
Why canot convert the Chinese into QR code ？？？

### ISSUE THREAD

**Issue by sexfio** [codebude/QRCoder#209]
Why canot convert the Chinese into QR code ？？？
Scan the code and it's garbled.

THX!

Dim qrGenerator As New QRCodeGenerator()
Dim qrCodeData As QRCodeData = qrGenerator.CreateQrCode("你好啊，我是中文", QRCodeGenerator.ECCLevel.Q, False, True, QRCodeGenerator.EciMode.Default)

Dim qrCode As New QRCode(qrCodeData)

**Comment by mikefoxnobel** [comment]
As my test, the Chinese result is right.
Platform: WPF
QR scanner: iPhone Camera

我测试的结果，输出的中文QR是正确的。
平台：WPF
扫描器：iPhone相机应用

**Comment by timothyparez** [comment]
I can also confirm this works properly.
It can generate the proper output and read it back with WeChat.
