### ISSUE TITLE
QRCode class no longer works properly on Mac OS when mono-libgdiplus is updated to version 6.0.4

### ISSUE THREAD

**Issue by manikata0** [codebude/QRCoder#210]
On both Mac os 10.14 and Mac os 10.15 when using the QRCode class to create QR code with custom logo inside, when mono-libgdiplus is updated to 6.0.4 , the QR code generated is mangled. The BitmapByteQRCode works fine with mono-libgdiplus and QR codes generated are spot on.
The project has the same behaviour on .Net Core versions 2.1,2.2,3.0 and 3.1 and was tested with QRCoder 1.3.5 and 1.3.6. Works fine on Windows

**Comment by manikata0** [comment]
The was isolated to be caused by mono-libgdiplus. I have removed the most up-to-date brew version -6.0.4 and manually installed 5.6.1 from their github repository and now QRCoder works fine

**Comment by codebude** [comment]
Unfortunately I have no MacOS environment to test this. But from the description it sound like an error with the libgdiplus. Does this error still occur with the latest libgdiplus version? And can you check if this still happens for the latest QR coder built. (Either compile from GitHub or take the latest build from the myget stream as described in our readme.)

**Comment by manikata0** [comment]
Hi Raffael, Apologies for the late reply! First of all I want to express my gratitude for your outstanding work on this library!The issue still persists on Mac OS, but it is working fine on Windows. When only QR codes are generated its fine on Mac OS as well, issue is only persistent when we create QR code with inset logo. I have attached 2 QR codes - one generated on Windows and one on Mac OS(the unreadable one). On Mac I am using the latest mono-libgdiplus from HomeBrew.
Do not hesitate to contact me should you have any further queries!
Kind Regards, Vasil 

    On Thursday, 26 March 2020, 21:31:33 GMT, Raffael Herrmann <notifications@github.com> wrote:  
 
 


Unfortunately I have no MacOS environment to test this. But from the description it sound like an error with the libgdiplus. Does this error still occur with the latest libgdiplus version? And can you check if this still happens for the latest QR coder built. (Either compile from GitHub or take the latest build from the myget stream as described in our readme.)

**Comment by codebude** [comment]
Hi @manikata0 ,

you responded to the notification mail from Github. This lead to an automatic comment in the Github issue. Unfortunatly the attachments from your mail were dropped by Github. Could you please open the issue in your webbrowser and manuelly comment/add/upload the files?

**Comment by jgcaballero** [comment]
Encountered a similar problem on MacOS where my project stopped working when updating mono-libgdiplus. I fixed it by [installing runtime.osx.10.10-x64.CoreCompat.System.Drawing](https://github.com/dotnet/core/issues/2746#issuecomment-593808044)

**Comment by josegomez** [comment]
@codebude having the same issue on Mac, I have  a Mac to test with if you'd like me to do some testing

**Comment by Sdraugel** [comment]
I fixed and tested it on my Mac.

https://github.com/codebude/QRCoder/issues/232#issuecomment-630852486

**Comment by codebude** [comment]
Hi @manikata0 ,

this issue should be solved with the merging of https://github.com/codebude/QRCoder/pull/245 thus I'll close the issue. If you experience any further problems, let me know so that I can re-open the issue or open a new issue. Thanks for being patient and apologizes for the slow response time!
