### ISSUE TITLE
libpng error:No IDATS written info file  GDI + general error

### ISSUE THREAD

**Issue by l2999019** [codebude/QRCoder#213]
I generate two-dimensional code in PNG format in Linux container
It works normally, but I get "libpng error:No IDATS written info file" error message occasionally
This error message doesn't appear every time, but it's about one percent of the time
Is there any good solution?

**Comment by l2999019** [comment]
Has this problem been solved?

**Comment by codebude** [comment]
Couldn't reproduce the problem and thus neither test nor fix it. But research shows that this seems to be related to System.Drawing/GDI(+) implementation. Since the plan is to port QRCoder away from System.Drawing to ImageSharp, these errors hopefully will be gone in the future.

**Comment by l2999019** [comment]
Thank you for your reply. I will continue to pay attention to the latest version
