### ISSUE TITLE
Generate qr in alphanumeric mode?

### ISSUE THREAD

**Issue by leandromendes-ifthen** [codebude/QRCoder#215]
Type of issue
[ ] Bug  
[X ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

Sorry for bothering but im new to the usage of qr code but to my understanding you can enconde only in alphanumeric mode. Does the librabry allow that or only data mix mode?

**Comment by codebude** [comment]
The library checks the data/payload you want to encode. If it contains only digits, it encodes in numeric mode. If it contains digits and a set of chars, it uses alphanumeric mode and for anything else it encodes the data in utf8/binary mode. If you want to encode in utf8/binary mode anyway (even if your payload consists only of e.g. digits) you can set the `forceUtf8` parameter as explained here: https://github.com/codebude/QRCoder/wiki/How-to-use-QRCoder
