### ISSUE TITLE
.NET Framework - "OnlyUseLatestCLR" Registry Setting

### ISSUE THREAD

**Issue by nshulak** [codebude/QRCoder#220]
## .NET Framework / Registry Settings

Immediately after installing the QRCoder.DLL we have an intermittent (but frequent) issue where an important registry setting is changed by an application or process.  The OnlyUseLatestCLR registry setting (under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework) is getting set to "1" every few days and this is causing many of our SSRS reports to fail (claiming it cannot locate Microsoft.VisualBasic.DLL).  Resetting the flag back to "0" corrects the issue.   We've turned on registry auditing but I'd like to see if anyone is familiar with this issue.

My thoughts are that I may need to re-compile either the QRCoder.DLL using a .NET framework version that matches the server framework version, or recompile the consuming application using this version, or both.  Suggestions will be appreciated.

SQL Server 2012
Windows Server 2008 R2
QRCoder v1.3.6.0 / Runtime version v4.0.30319
Server .NET Frameworks:  v2.0.50727, v3.0, v4.0.30319

**Comment by codebude** [comment]
Hi @nshulak ,
I'm sorry but I can't explain why this happened. I never had this situation/have seen such behaviour. But I guess this issues is not really related to QRCoder but more are general "issue" with .NET. But it's just a guess.

I've seen that you posted your question also in the Microsoft forum/board. Did you get any answer there?

**Comment by codebude** [comment]
Closed since no feedback received for over a year. If this problem arises again, feel free to re-open the ticket.
