### ISSUE TITLE
Allow generation with 8 Digit Hex Values

### ISSUE THREAD

**Issue by leandromendes-ifthen** [codebude/QRCoder#221]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[X] Request for new feature/improvement  

Is it possible to add suport for opacity in hex values when generating qr codes?

## Expected Behavior
Bitmap qrCodeImage = qrCode.GetGraphic(1, #050303c2, #050303c2, true);
Im generating hex codes that come in 8 digits instead of the usual six.
If my tests are correct right now it only allows for 6 digits hex codes resulting in different color generated codes.

**Comment by codebude** [comment]
Hi @leandromendes-ifthen ,

it works also with transparency. Therefore please pass 8 digits (whereby the first two digits are the alpha transparency: `#<AA><RR><GG><BB>`).

There are two things which should be noted:

- This works only with the QRCode-class (not with BitmapByteQRCode or PngByteQRCode).
- To "see" the transparency you must save the QR code image created in an image format that supports transparency (like PNG or GIF)

I ran the following sample code:
```csharp
using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
{
	using (QRCodeData qrCodeData = qrGenerator.CreateQrCode("1234567890", QRCodeGenerator.ECCLevel.L))
	{
		using (QRCode qrCode = new QRCode(qrCodeData))
		{

			//Set dark modules with transparency
			var img = qrCode.GetGraphic(20, "#05000000", "#ffffff");
			img.Save(@"C:\path\to\disk\image.png", ImageFormat.Png);
		}
	}
}
```

And then layed the graphic onto another in Paint.NET. The outcome definitely has some transparency. ;-)

![argb-sample](https://user-images.githubusercontent.com/2236234/77678162-0b5ff300-6f91-11ea-90d1-03bea3cccd43.png)

Feel free to re-open the issue, if you have any further questions.
