### ISSUE TITLE
string misbehave while scan QRCode and sometimes QRCode Generate Empty

### ISSUE THREAD

**Issue by syedmca72** [codebude/QRCoder#222]
**1. String Misbehave while scan of QRCode like 'n' replaced with some other character or some special character.**
**2. String of "QRCode is Empty While Scanning"**
Season :- ORCHESTRA HIVER 20; Theme :- EMERALD NIGHT; Style :- UVALEE-AT(UVALEE-AT); Vendor :- PERMESHWAR-OI; Activity :- SMS dispatch to C.O.; Color :- VEM, Size :- S; Particular :- BLUEDART#36591853325; Submission Date  :- 23-Nov-2019; Qty :- 1; IDList :- ORCFRC60; 
[PrintQRCode_CantScan.PDF](https://github.com/codebude/QRCoder/files/4089768/PrintQRCode_CantScan.PDF)

below is my code plz help me.

#region " QRCode "
        public string GenerateQRCode(string sText, int Height = 150, int Width = 150)
        {
            if (Strings.IsNullOrEmpty(sText)) return "";

            string sFileName = sText + "_" + DateTime.Now.ToString("ddmmyyhhssmm") + ".png";
            string sBarCodeImagePath = oContext.oCore.ApplicationPathFileServer + "QRCode\\" + "QRTracking_" + DateTime.Now.ToString("ddmmyyhhssmm") + ".png";
            //string sBarCodeImagePath = oContext.oCore.ApplicationPathFileServer + "QRCode\\" + FixFileName(sFileName);           

            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeGenerator.QRCode qrCode = qrGenerator.CreateQrCode(sText, QRCodeGenerator.ECCLevel.Q);
            System.Web.UI.WebControls.Image imgBarCode = new System.Web.UI.WebControls.Image();
            imgBarCode.Height = Height;
            imgBarCode.Width = Width;

            try
            {
                using (Bitmap bitMap = qrCode.GetGraphic(20))
                {
                   
                    bitMap.Save(sBarCodeImagePath, System.Drawing.Imaging.ImageFormat.Png);

                    return sBarCodeImagePath;
                }

            }
            catch (Exception ex) { sFileName = ""; }

            return sBarCodeImagePath;
        }

        #endregion

**Comment by codebude** [comment]
Hi @syedmca72 - what is the value you are encoding in the code? (With view onto your code - what's the value of  `sText`?)

**Comment by syedmca72** [comment]
hello,
string for QRCode:
Season :- ORCHESTRA HIVER 20; Theme :- EMERALD NIGHT; Style :-
UVALEE-AT(UVALEE-AT); Vendor :- PERMESHWAR-OI; Activity :- SMS dispatch to
C.O.; Color :- VEM, Size :- S; Particular :- BLUEDART#36591853325;
Submission Date  :- 23-Nov-2019; Qty :- 1; IDList :- ORCFRC60;

**Comment by codebude** [comment]
When I create a QR code with this string and your code above (ECCLevel = Q, ImageFormat = PNG) I get a totally fine and scanable QR code. But the code also looks different to your one you posted in the linked PDF document in your initial post.

Which version of the library did you use? Have you tried using the latest dev build? (Either compile it yourself from Github/code or by use of the MyGet feed as additional package source in your Nuget client:  https://www.myget.org/F/qrcoder/api/v3/index.json )

**Comment by codebude** [comment]
Issues closed since author of the issue doesn't respond. @syedmca72 if you still want to solve the problem, let me know, then I'll re-open the ticket.
