### ISSUE TITLE
Does not work correctly in multi-threaded evnironment

### ISSUE THREAD

**Issue by thegreygod** [codebude/QRCoder#226]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
Can you please give more details? What happens what shouldn't happen? Which errors occur in what cases? How does your environment look like?

**Comment by codebude** [comment]
Closed since author of the issues gave no feedback/no enough information to handle the issue.

**Comment by thegreygod** [comment]
I didn't comment because I didn't see the questions above.

**Comment by codebude** [comment]
Hy @thegreygod ,
No problem. Then I'll reopen the issue. Can you please provide more details (e.g. how does the error look like? How can it be reproduced? ...)

**Comment by codebude** [comment]
Hy @thegreygod ,
No problem. Then I'll reopen the issue. Can you please provide more details (e.g. how does the error look like? How can it be reproduced? ...)

**Comment by codebude** [comment]
Closed because no feedback was given. If this problem still exists, please re-open the ticket and provide additional information.
