### ISSUE TITLE
Icon without rounded corners

### ISSUE THREAD

**Issue by fluflo** [codebude/QRCoder#230]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ X] Request for new feature/improvement  

## Expected Behavior
If you add an Icon to the QR-Code the icon has a normal corners.

## Current Behavior
If you add an icon to the QR-Code the icon has rounded corners

## Possible Solution (optional)
Add a possiblity to define, if I want my icon to have rounded borders.

## Your Environment
* Version used:  
*  NuGet package
* Used payload generator:  URL
* Used ECC-level:  L
* Used renderer class:  Base64QRCode
* .NET 4.7.2

**Comment by codebude** [comment]
Since we removed the graphics "Region" code from the project (due to serious problems on Linux environments) your code suggestions for rounded corners won't be added to the project. I suppose to prepare the icon/logo itself with rounded corners instread.
