### ISSUE TITLE
41 character bug

### ISSUE THREAD

**Issue by morrowind** [codebude/QRCoder#236]
## Type of issue
 [ x ] Bug  
 [ ] Question (e.g. about handling/usage)  
 [ ] Request for new feature/improvement  

## Expected Behavior
The QR code generated by 41 characters shall can be recognized.

## Current Behavior
The QR code generated by 41 characters cannot be recognized.

## Steps to Reproduce (for bugs)
1. 
```
QRCoder.QRCodeData code_data = code_generator.CreateQrCode("some string", QRCoder.QRCodeGenerator.ECCLevel.H, true, true, QRCoder.QRCodeGenerator.EciMode.Utf8);
```
Note the length of "some string" should be 41, the content can be any ASCII characters, and the 4th parameter is set as `true`.

2. Use the `code_data` to generate a bitmap. 
```
QRCoder.QRCode code = new QRCoder.QRCode(code_data);
Bitmap bmp = code.GetGraphic(3, Color.Black, Color.White, true);
```
3. Show the bmp on screen, use other application to scan the code.
4. The QR code of bmp cannot be recognized.

## Your Environment
Windows with .NetFramework v4.6

**Comment by elisy** [comment]
I can reproduce in 32 string length: 
`            
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("https://www.gallery.kz/p/20309pi", QRCodeGenerator.ECCLevel.Q, true, false, QRCodeGenerator.EciMode.Utf8);
QRCode qrCode = new QRCode(qrCodeData);
using (Bitmap image = qrCode.GetGraphic(pixelsPerModule, Color.Black, Color.White, true))
`
![qrcore-error](https://user-images.githubusercontent.com/2704050/93292384-4851c780-f807-11ea-887a-a5ed8e89a1da.jpg)

If you change string with the same length the qrcode will be nonrecognizable too.

**Comment by codebude** [comment]
Hi @morrowind ,

I could re-produce the error. It happened if someone used ECI-mode and entered a payload which maxed out a specific QR code version. Unfortunately the additional headers for ECI mode weren't taken into size calculation. 

The error was fixed in: https://github.com/codebude/QRCoder/commit/012dee3edb5be2508f35ebc6a3d1d9311dc2c256
And thus will be publicly available with the next Nuget package update.
