### ISSUE TITLE
Change size of AsciiQRCode

### ISSUE THREAD

**Issue by nhh** [codebude/QRCoder#237]
Is there a possibilty to reduce the size from a asciiqrcode?

Is unreadable big inside a command line.

I know you can change the black and whitespace characters. May someone point me to appropriate values?

The actual output for a medium sized string is nearly as large as my 1080p screen.

Thanks!

**Comment by codebude** [comment]
Hi @nhh ,

this isn't really possible... The only chance I see is to lower the font size in your terminal (but then all other stuff might become unreadable...). The more data you store inside a qr code the bigger it gets (in terms of black and white modules or in case of ASCII qr codes in terms of characters per terminal line). So either store less data in the QR code or lower the font-size/allow more characters per line in your terminal.

**Comment by rgl** [comment]
Could it be half the size if it would use the following characters?

```
ASCII code 219 = █ ( Block, graphic character )
ASCII code 220 = ▄ ( Bottom half block )
ASCII code 223 = ▀ ( Top half block )
```
