### ISSUE TITLE
QRCoder can support SVG?

### ISSUE THREAD

**Issue by shfee** [codebude/QRCoder#24]
QRCoder can support SVG?

**Comment by codebude** [comment]
At the moment it's not possible. But you could implement it yourself, by either creating a new QRCode class by implementing AbstractQRCode or just overwrite the existing GetGraphics-method.

**Comment by codebude** [comment]
Hi @shfee - i just implemented a simple SVG feature. You can read about the usage in the readme file. https://github.com/codebude/QRCoder/blob/master/readme.md

The Commit with the SVG code is: https://github.com/codebude/QRCoder/commit/adc817a59a5d9144d65860b7b6d4dd9c0c70bb1c
