### ISSUE TITLE
[New Feature]support for art qrCode

### ISSUE THREAD

**Issue by serfend** [codebude/QRCoder#241]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[*] Request for new feature/improvement  

## Expected Behavior
may be you can referer to [/sylnsfar/qrcode](https://github.com/sylnsfar/qrcode)
![https://github.com/sylnsfar/qrcode/raw/master/example/qrs2.jpg](https://github.com/sylnsfar/qrcode/raw/master/example/qrs2.jpg)

**Comment by Pushan12** [comment]
can we have something like 

![image](https://user-images.githubusercontent.com/21195975/88824545-1ac3a700-d1e4-11ea-8787-c2845cab7ea1.png)

refer : [QrMonkey](https://www.qrcode-monkey.com/)

**Comment by codebude** [comment]
Hi @serfend , hi @Pushan12 ,

currently there is no rendering class, which creates such "artistic" QR code graphics. But feel free to write your own renderer. Therefore have a look at the QRCode class (https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCode.cs) as also at the AbstractQrCode class (https://github.com/codebude/QRCoder/blob/master/QRCoder/AbstractQRCode.cs). As you can see all renderers work with the abstract class. So create a new class like "ArtQRCode.cs" which implements AbstractQRCode and write the rendering logic to draw such QRCodes. Additional information can be found here: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers

If you have implemented such renderer, feel free to send in a merge request.

**Comment by codebude** [comment]
Those types of codes can now be generated with the ArtQRCode rendering class which is available in the latest CI build and from 1.4.2 of the official build. (I will release 1.4.2 soon on Nuget.)
