### ISSUE TITLE
Use GetGraphic with SixLabors.ImageSharp.Color instead of System.Drawing.Color

### ISSUE THREAD

**Issue by AlphaComposite** [codebude/QRCoder#253]
From the documentation example, we're trying to add an icon to the center of the QR Code. 

qrCode.GetGraphic(pixelsPerModule, Color.Black, Color.White, Image.Load("C:\\myimage.png"))

We need to use Sixlabors.ImageSharp.Color instead because we're running on a cross-platform Linux environment and we've had consistent problems trying to run System.Drawing (memory leaks, for one) on Linux so we're using SixLabors instead. 

Has anyone else done this? It looks like the QRCoder GetGraphic method is tied to System.Drawing. 

I'm open to a workaround.

**Comment by codebude** [comment]
Hi @AlphaComposite ,

in general I don't plan to switch away from System.Drawing in near future, but I see multiple options for your specific problem:

1. If you are just struggeling to pass the (System.Drawing.)Color-values to the GetGraphic method, you can use another overload which takes the color values as hex strings (e.g. "#000000" for black). Check "overload 3" in the documentation: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#21-qrcode-renderer-in-detail
2. If you need a QRCode class which doesn't use System.Drawing at all, you could switch to [BitmapByteQrCode](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#24-bitmapbyteqrcode-renderer-in-detail) or [PngByteQrCode](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#25-pngbyteqrcode-renderer-in-detail) rendering classes.
3. If you're not fine with the renderers above, you could implement your own by writing your own class that inherits "AbstractQrCode" class or use the data/raw export ([check this](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-raw-data-export)) and render it in any other tool.

If you have further questions, feel free to comment here.
