### ISSUE TITLE
Binary QR codes?

### ISSUE THREAD

**Issue by dantechguy** [codebude/QRCoder#257]
## Type of issue
[ ] Bug  
[X] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Is there any way to generate a QR code from binary data? I suppose it is possible to base64 encode it into text, but that seems a little inefficient given that QR codes *can* support binary data. Also, I don't know if the standard string encoding is ASCII only or not, and if not then base64 would be even less efficient to support the increased number of characters.

Thanks for your help!

**Comment by codebude** [comment]
Hi @dantechguy ,

> Is there any way to generate a QR code from binary data?

currently there's no overload to pass binary data (e.g. a byte[]) to QRCoder when generating QR codes. All methods of QRCoder expect a String as payload.

> [...] but that seems a little inefficient given that QR codes can support binary data

Not only can QR codes encode binary data, but QRCoder already makes use of it. Depending on the given payload/string, QRCoder checks if the payload string is Numeric only, Alphanumeric only or if it contains more chars. If it's neither numeric nor alphanumeric only, QRCoder encodes the string in byte mode. Check the following three methods:

- https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCodeGenerator.cs#L124
- https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCodeGenerator.cs#L881
- https://github.com/codebude/QRCoder/blob/master/QRCoder/QRCodeGenerator.cs#L1021

> Also, I don't know if the standard string encoding is ASCII only or not [...]

Check the explanation above. Strings/payloads are encoded depending on their content.
