### ISSUE TITLE
QR Image White margins

### ISSUE THREAD

**Issue by shfee** [codebude/QRCoder#27]
Hi, How to do setting QR Image White margin?margin than Larger

**Comment by shfee** [comment]
![1](https://cloud.githubusercontent.com/assets/17747897/13877311/e5f1738c-ed44-11e5-9696-ff390e6ac0ca.png)

**Comment by codebude** [comment]
Hi @shfee, the "margins" are defined as quiet zones in the QR code iso specification. They are are official part of each and every QR code. 

Nevertheless, last week I was asked, how to remove them. So I added a switch to remove the margins.  Have a look at the issues: https://github.com/codebude/QRCoder/issues/25
If you want to make them larger, you could reverse the removement logic.

Another option would be, to place the ready rendered QR code image centered onto a slightly larger Bitmap.

**Comment by shfee** [comment]
Thank you!
