### ISSUE TITLE
QR Code doesn't work

### ISSUE THREAD

**Issue by SkChris** [codebude/QRCoder#270]
## Type of issue
[ ] Bug  
[x] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Hi, I am using the Bezahlcode Payload of the payload generator in the vb.net framework 4.5
Using the below code I am expecting the generated QR Code to work.

        Dim generator As New BezahlCode(BezahlCode.AuthorityType.singlepaymentsepa, "Testname", iban:="AT123412341234123456", bic:="BAWAATWW", amount:=100.00, reason:="Test")
        Dim payload As String = generator.ToString()
        Dim qrGenerator As New QRCoder.QRCodeGenerator
        Dim qrCodeData As QRCoder.QRCodeData = qrGenerator.CreateQrCode(payload, qrGenerator.ECCLevel.Q)
        Dim qrCode As New QRCoder.QRCode(qrCodeData)
        Dim qrCodeasBitmap As Bitmap = qrCode.GetGraphic(5)
        QRCodePic.BackgroundImage = qrCodeasBitmap

## Current Behavior
The QR code can't be read by multiple banking app readers.

## Possible Solution (optional)
Any idea?

## Your Environment

* Version used:  
* NuGet Package
* Payload/Encoded text:  
* Used payload generator:  Bezahlcode
* Used ECC-level:  Q
* Used renderer class:  
* Environment (.NET 4.5)

**Comment by codebude** [comment]
Hi @SkChris ,

Bezahlcode is only one of several standards for mapping remittance information into QRCodes. Whether an app can read a code depends on whether the app developer has implemented the respective code standard. Bezahlcode generally seems to be on the decline. (The website with the technical specification, for example, is no longer online). 

Have you tried using an alternative code type like "Girocode"? This is also supported by the QRCoder Payload Generator. (You can find more information on Girocode in our Wiki: https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#37-girocode )
