### ISSUE TITLE
Add Organization in the ContactData payload

### ISSUE THREAD

**Issue by giccifelipe** [codebude/QRCoder#274]
Hi,

I would like to know if there's a way to add an Organization name in the ContactData payload?

Regards,
Felipe

**Comment by raganca** [comment]
I had this issue too, so I went ahead and put in a fix! Hopefully it's accepted soon.

Cheers,
-cr

**Comment by giccifelipe** [comment]
Yeah, I've done something similar but manually until they accept the pr and we can get an update. Hope soon as it's been a while hehe.

**Comment by codebude** [comment]
Hi @giccifelipe , hi @raganca ,

please excuse the late reply. Thanks for your input and support. I would really love to merge the changes from @raganca , but at first one, two small things should be re-written, to make the changes non-breaking for other users. If you could change the affected parts of your PR, I will merge it.

**Comment by codebude** [comment]
PR successfully merged. Thanks for your support @raganca  and @giccifelipe
