### ISSUE TITLE
.NET Standard 2.1 Support

### ISSUE THREAD

**Issue by xshiiiidev** [codebude/QRCoder#275]
Please update the library to support .NET Standard 2.1.

Thank you so much.

**Comment by LordZoltan** [comment]
.netstandard2.0 libraries can be dependencies of 2.1 libraries and are guaranteed to work on pretty much every conceivable platform & runtime you can imagine - so what would be the point of just adding another target framework?

**Comment by xshiiiidev** [comment]
I encountered a problem before I thought it was related to this problem. Then later I tested and it's working with the 2.1. I will be closing this now thank you for the reply @LordZoltan.
