### ISSUE TITLE
How to generate QR Code that is supported by UPI apps like Phonepe, Paytm, Google Pay

### ISSUE THREAD

**Issue by subhojit-me** [codebude/QRCoder#277]
[ ] Bug  
[x] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Tring to generate a QR Code that can be used to pay via UPI

## Current Behavior
there is no Payload Generator that supports UPI, if exists and am missing that please correct me.

**Comment by subhojit-me** [comment]
after some study am  successfully able to find that QR Code for UPI payment can be done by passing string in upi:// format with parameter specified in this [doc](https://developers.google.com/pay/india/api/web/create-payment-method)

**Comment by codebude** [comment]
Thanks for pointing me to the UPI standard. Will add it to the todo list.

**Comment by subhojit-me** [comment]
Well, i used a trick about payto, did some research also to figured it out.

first i was using this [API](https://upiqr.in/) and generated a QR code and after scanning it with this app in [android](https://play.google.com/store/apps/details?id=com.gamma.scan&hl=en_IN&gl=US) it shows like this
![WhatsApp Image 2021-03-16 at 1 38 24 PM](https://user-images.githubusercontent.com/30930967/111276533-718bcd00-865d-11eb-887a-c0ae4d4ab330.jpeg)


So i tried the text as Payload in my code like this
```
var payload = $@"upi://pay?cu={upiParams.CURRENCY_CODE}&pa={upiParams.RECEIVER_VPA}&pn={upiParams.RECEIVER_NAME}&tn={upiParams.PAYMENT_NOTE}&am={upiParams.AMOUNT}";
QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q);
var qrCode = new Base64QRCode(qrCodeData);
```

and gotcha, its working
