### ISSUE TITLE
Icon on SVG QR Code

### ISSUE THREAD

**Issue by wyeack** [codebude/QRCoder#281]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x ] Request for new feature/improvement  

Would it be possible to add an overload to create an SVG QR with a center icon?

**Comment by codebude** [comment]
Hi @wyeack ,

I added a new optional parameter "logo" to the SvgQRCode constructors. By use of this parameter you can render logos (either raster graphic-based or vector based) onto SVG qr codes. Changes came with this commit: https://github.com/codebude/QRCoder/commit/9fe1f2bcbf15dd8901f850d82658a6f4de6f0d16

**Comment by wyeack** [comment]
Hi @codebude - would you be able to push it to NuGet?  I'm on 1.4.1 and I don't see that overloaded constructor.
