### ISSUE TITLE
Unable to load shared library 'libgdiplus'

### ISSUE THREAD

**Issue by eduardoxvii** [codebude/QRCoder#283]
## Type of issue
[x ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Qrcode is not generated in Centos 7

## Current Behavior
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
       ---> System.DllNotFoundException: **Unable to load shared library 'libgdiplus' or one of its dependencies.** In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
         at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
         at System.Drawing.SafeNativeMethods.Gdip..cctor()
         --- End of inner exception stack trace ---
         at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, IntPtr scan0, IntPtr& bitmap)
         at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
         at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule, Color darkColor, Color lightColor, Boolean drawQuietZones)
         at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule)

## Your Environment
Include as many relevant details about the environment you experienced the bug in.  

```
using (MemoryStream ms = new MemoryStream())
            {
                QRCodeGenerator qrGenerator = new QRCodeGenerator();
                var qrCodeData = qrGenerator.CreateQrCode($"{systemInformacoes.getSignConfirmation()}{id}", QRCodeGenerator.ECCLevel.Q);
                var qrCode = new QRCode(qrCodeData);
                var qrCodeImage = qrCode.GetGraphic(10); <-- The error appears here!!!                
}
```

* Version used:  1.4.1
* Compiled from source or NuGet package?:  Nuget
* System: CENTOS 7
* Payload/Encoded text:  
* Used payload generator:  
* Used ECC-level:  
* Used renderer class:  
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  net5.0

**Comment by dnoonan** [comment]
Installing libgdiplus worked for me. I'm on Pop!_OS 20.04.

`sudo apt install libgdiplus`

**Comment by eduardoxvii** [comment]
> sudo apt install libgdiplus

@dnoonan , worked!!!!!
But i needed run:
`yum install libgdiplus`
For Linux CentOs 7

**Comment by resting** [comment]
`brew install mono-libgdiplus` for mac users works
