### ISSUE TITLE
No Organization Value for VCARD2.1 to VCARD 4

### ISSUE THREAD

**Issue by cheahengsoon** [codebude/QRCoder#288]
## Type of issue
[X] Bug  
[X] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
The VCard should had the Organization value, I had go through from VCARD2.1,VCARD3,and VCARD 4 also cant see the organization value

## Current Behavior

Currently,VCARD2.1,VCARD3,and VCARD 4  did not shown the organization value
<img width="508" alt="VCard3" src="https://user-images.githubusercontent.com/2833325/117823120-b881f180-b29f-11eb-9ffc-bc1e7c6bacf3.png">

## Steps to Reproduce (for bugs)
Here with my code snip
`   ContactData generator = new ContactData(ContactData.ContactOutputType.VCard3, firstname, lastname, knownas, officeMobile, officeMobile, officeMobile, emailaddress,null,"","","","","","","","");`

## Your Environment
* Version used:  1.4.1
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  ASP.NET FRAMEWROK 4.7.2

**Comment by codebude** [comment]
Hi @cheahengsoon ,

the organization was just added to the library. (Within the follow PR https://github.com/codebude/QRCoder/pull/276 )
Currently the feature is only available in the nightly builds: https://www.myget.org/feed/qrcoder/package/nuget/QRCoder (e.g. version 1.4.2-CI0000008)

The feature will show up in the official Nuget package when the next version (1.4.2) is officially released.
