### ISSUE TITLE
iconBorderWidth Doesn't work

### ISSUE THREAD

**Issue by kuenzign** [codebude/QRCoder#291]
## Type of issue
[x] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
The `iconBorderWidth` parameter is supposed to specify a border to be drawn around an icon inside the QR code.

## Current Behavior
Currently, no border is drawn around icons.

## Possible Solution (optional)
It looks like #245 broke this functionality.

## Steps to Reproduce (for bugs)
Create a `QRCode` and call the `GetGraphic()` function while passing in a bitmap for the icon and a value greater than 1 for `iconBorderWidth `.  Notice that the generated graphic does not have a border around the icon.

## Your Environment
Nuget package 1.4.1

**Comment by kuenzign** [comment]
Yes, that is the commit from the pull request that I stated...

**Comment by codebude** [comment]
Hi @kuenzign , hi @DamienLaw ,

I refactored the code and added the functionality again. (But in a different manner without using Region.Exclude, which lead to problems on Linux systems in the past.) The new function behaves as follows:
- If iconBorderWidth isn't set, the (new) default value of 0 triggers that no border/background is drawn. (=Same behaviour as before the code changes of this issue.)
- If iconBorderWidth is set and iconBorderWidth > 0, the background/border is drawn as requested by you in this issue (=behaviour as it was before the code broke...)
- A new (and optional) parameter called `iconBackgroundColor` can be set to define the color of the border/background of the icon. If iconBackgroundColor isn't set, its default value (`null`) kicks in and QRCoder chooses the lightColor as icon border/background color. You can checkout the new paramter [in our wiki](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#21-qrcode-renderer-in-detail), too.

**Comment by kuenzign** [comment]
What nuget package release will this fix be included in?

**Comment by codebude** [comment]
In NuGet version 1.4.2. This was the last issue I planned to resolve before publishing 1.4.2. So it will be publicly available within the next couple hours.

**Comment by codebude** [comment]
It's live now. Feel free to check the also new release notes page, to see what has changed in 1.4.2 besides the icon background: https://github.com/codebude/QRCoder/wiki/Release-notes

**Comment by DamienLaw** [comment]
It seems that `iconBackgroundColor ` is only available to the class `QRCode` only and not `Base64QRCode`. I think it would be a nice addition to all types of QR Code renderers.
