### ISSUE TITLE
Transparent barcodes

### ISSUE THREAD

**Issue by NigelThorne** [codebude/QRCoder#294]
I've been hacking a new renderer for your library to make it possible to have see though barcodes. 

![image](https://user-images.githubusercontent.com/5942/119067919-7175c800-ba26-11eb-974a-1339fa2b57c3.png)

I wrote a version of the QRCode class to do this. If you are keen I'll raise a pull request, and you guys can make it production ready. 
Let me know if you are keen.

**Comment by codebude** [comment]
Merged it. Thank you very much - great piece of work!
