### ISSUE TITLE
SMS text is not prefilled on iOS messaging app 

### ISSUE THREAD

**Issue by donataskib** [codebude/QRCoder#296]
Hello,

Text is not being prefilled on iOs messaging app when using SMS payload.

This is my code. On android it works correctly, but not on iOs. It just prefills phone number correctly.
```
var smsGenerator = new PayloadGenerator.SMS(phoneNumber, text);
var payload = smsGenerator.ToString();

var qrGenerator = new QRCodeGenerator();
var qrCodeData = qrGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q);
var qrCodeBytes = new BitmapByteQRCode(qrCodeData).GetGraphic(pixelsPerModule);
```

Regards,
Donatas

**Comment by codebude** [comment]
Hi @donataskib ,

iOS expects a differently formatted payload. Unfortunately there isn't (or at least I'm not aware of) a format, that works on Android and iOS at the same time.

To generate a SMS for iOS, just pass the Encoding as third parameter:
```csharp
var smsGenerator = new PayloadGenerator.SMS(phoneNumber, text, SMSEncoding.SMS_iOS);
```

**Comment by donataskib** [comment]
Thank you.

After I wrote a comment, I tried changing encoding which worked for both iOs and Android: 
`var smsGenerator = new PayloadGenerator.SMS(phoneNumber, text, SMSEncoding.SMSTO);`

Tried this on Android 11 and iOS 11 and worked. 

Still, thank you. We can close this :)
