### ISSUE TITLE
XamlQRCode not found

### ISSUE THREAD

**Issue by GF-Huang** [codebude/QRCoder#297]
![image](https://user-images.githubusercontent.com/4510984/119214067-7609b180-baf6-11eb-9a4e-2ed67b05ee22.png)

## Type of issue
[ ] Bug  
[x] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior
Found

## Current Behavior
Not Found

## Your Environment

* Version used:  `1.4.1`
* Compiled from source or NuGet package?:  `NuGet`
* Payload/Encoded text:  
* Used payload generator:  `Yes`
* Used ECC-level:  `Q`
* Used renderer class:  `XamlQRCode`
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  `.NET 5`

**Comment by codebude** [comment]
.NET5 support will come with the next release. (Within the next 14 days.) In 1.4.1 XamlQRCode is only support when full (classic) .NET Framework is selected as target.

**Comment by GF-Huang** [comment]
Thanks reply.
