### ISSUE TITLE
Render and resize for web display?

### ISSUE THREAD

**Issue by DarthSonic** [codebude/QRCoder#299]
## Type of issue
[ ] Bug  
[x ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Your Environment
ASP.NET MVC

Currently I am using QRCode class and resize the Bitmap of GetGraphic method. Then I place the BMP as Base64 image on webpage.

Problem is: The QRCode gets blurry when resizing to 96x96px.

How can it be done with high quality render?

**Comment by saxmaster79** [comment]
Maybe you could use the [SvgQRCode-Renderer](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#26-svgqrcode-renderer-in-detail)
