### ISSUE TITLE
How to remove border if I don't need one?

### ISSUE THREAD

**Issue by MaslovD** [codebude/QRCoder#301]
## Type of issue
[ ] Bug  
[+] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
Hi @MaslovD ,

just set the parameter "drawQuietZones" to _false_. You can read more about the parameters in our wiki: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#21-qrcode-renderer-in-detail
