### ISSUE TITLE
How to add Job Title in Vcard v3

### ISSUE THREAD

**Issue by cheahengsoon** [codebude/QRCoder#303]
## Type of issue
[ ] Bug  
[X ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Your Environment
* Version used:  v3
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .Net 4.5

May I ask about how to add Job Title in the VCard?
```
ContactData generator = new ContactData(ContactData.ContactOutputType.VCard3, ......)
            string payload = generator.ToString();

```

**Comment by cheahengsoon** [comment]
I solved by myself

**Comment by fatihdurgut** [comment]
Can you share your solution with us?
