### ISSUE TITLE
Adding profile photo vCard QR

### ISSUE THREAD

**Issue by sgkalyans** [codebude/QRCoder#306]
Hi there 

Is there any way to render QR code with profile picture in VCard? 

I'm getting too large error when I render QR code for vCard wjat profile picture. 

Hope to have some sample codes for this. 

Thank you

**Comment by codebude** [comment]
Theoretically it's possible to save a vCard including profile picture inside a QR code. You just have to ensure, that the picture is "small enough". [This table](https://blog.qr4.nl/page/QR-Code-Data-Capacity.aspx) shows how much data can be saved inside a QR code. 
Following the table, the biggest QR code format (=version 40) with the lowest error correction rate (ECCLevel=L) can store up to 2953 byte of data. Just descrease the profile picture's size inside the vCard that much, that the complete vCard string/payload isn't bigger than 2953 byte and you're good to go. ;-)
