### ISSUE TITLE
Info. Demo QRCoderArt project at the base reflection QRCoder.dll + QRCoderDemo

### ISSUE THREAD

**Issue by AlexandreZaytsev** [codebude/QRCoder#310]
Hello everyone. 
A small application for testing qrcoder.dll through reflection
[Demo QRCoderArt](https://github.com/AlexandreZaytsev/QRCoderArt)
...
didn't implement some payloads (with nested classes), I didn't have enough knowledge...
i continue to work on this, if anyone is interested - join ))

**Comment by AlexandreZaytsev** [comment]
Raffael Herrmann - please add a constructor for One-Time-Password class
for use in reflection
?
))

**Comment by AlexandreZaytsev** [comment]
everything is ready

**Comment by codebude** [comment]
Hello @AlexandreZaytsev ,

do you mind adding your ["ArtQRCode.cs"](https://github.com/AlexandreZaytsev/QRCoderArt/blob/master/ArtQRCode.cs) via Pull Request to our repository? I would love to integrate it as an offical part of QRCoder.

**Comment by AlexandreZaytsev** [comment]
Hello! ))
file: - ArtQRCode. cs - not mine! )) I took it from the project NigelThorne (https://github.com/codebude/QRCoder/pull/295) (https://github.com/codebude/QRCoder/tree/91839cfe9c445832a61a993893eccfab9e264ee8/QRCoder)
...
so this is a question for him ))
it would be nice if you (in one form or another) built it into your qrcoder.dll

ps
mine is just a test application (QRCoderArt) based on your demo project (to show the capabilities of your library), if it suits you-of course, take it! ))

**Comment by codebude** [comment]
Closing this issue, since adding ArtQRCode.cs was already handled/done in #295
