### ISSUE TITLE
Payload extension (localization)

### ISSUE THREAD

**Issue by AlexandreZaytsev** [codebude/QRCoder#316]
hello everyone!
for example,
a local payload from Russia has been added ))
`public class RussiaPaymentOrder : PayloadGenerator.Payload`
Standards of financial transactions. Two-dimensional barcode symbols for payments by individuals (ГОСТ Р 56042-2014)

see project 
https://github.com/AlexandreZaytsev/QRCoderArt
file: PayloadExt.cs
https://github.com/AlexandreZaytsev/QRCoderArt/blob/master/PayloadExt.cs

**Comment by codebude** [comment]
Hi @AlexandreZaytsev ,

do you mind, if I integrate your RussiaPaymentOrder class officially into QRCoder?

**Comment by AlexandreZaytsev** [comment]
Hi, yes of course 
([here](https://roskazna.gov.ru/upload/iblock/5fa/gost_r_56042_2014.pdf) is the full specification of the format (in Russian)

**Comment by codebude** [comment]
Hi Alex, 
thanks again for pointing me to this new payload format. I took your class and added some more validation/documentation. Since I don't speak russian, I had to work a lot with Google Translate. So if you find any transaltion errors, let me know.
