### ISSUE TITLE
Add organisation title to contact

### ISSUE THREAD

**Issue by giccifelipe** [codebude/QRCoder#324]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior

When creating a contact card, I would like to send an option for Organisation Title as in 'Web Developer', 'Accounting', 'Sales Manager', ...

## Current Behavior

No option to add Organisation title in the ContactData class.

## Possible Solution (optional)

Add extra property 'orgTitle', string, null, 'Organization/Company Title' in the ContactData class

## Your Environment

* Version used:  1.4.1
* Compiled from source or NuGet package?:  Yes
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .Net Code 3.1 -> migrating to .NET 5/6

**Comment by codebude** [comment]
Thanks for your help! 👍
