### ISSUE TITLE
Invalid / corrupted QR Code 

### ISSUE THREAD

**Issue by Armin234** [codebude/QRCoder#330]
Hi,

I'm using .Net 4.5 und Nuget version 1.4.1 of QRCoder, and I'm getting an invalid / corrupted
QR-Code for the Data = "A11".
The generated QR-Code has only 20 Lines, instant of 21 lines as the QR-code generated for "A05"

QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("A11" , QRCodeGenerator.ECCLevel.H);
AsciiQRCode qrCode = new AsciiQRCode(qrCodeData);

string lF = qrCode.GetGraphic(1, "1", "0", "\n");

Is there any workaround ?

Regards Armin

**Comment by codebude** [comment]
Thank you both for your input! I found and fixed the bug in #339 
If you want to test the changes, feel free to use the latest [CI-build nuget package](https://github.com/codebude/QRCoder/packages) (Should be available within 10 minutes.) or wait for the 1.4.2 release on Nuget.org.
