### ISSUE TITLE
QRCode Console Demo Doesn't Write Multiple Image File Types

### ISSUE THREAD

**Issue by mishfit** [codebude/QRCoder#34]
Taken from suggestions in #33 

I'd be glad to work on it as it's helping me understand the API

**Comment by codebude** [comment]
Added multiple filetype support some hours ago... ;-)

https://github.com/codebude/QRCoder/commit/a727b826b42579be57dc072fa10e57ac5fa37a38

**Comment by mishfit** [comment]
Nope. Looks good, nothing to add there.

I'd like to take a stab at Stdin (piping from command line directly into QRCoderConsole)
