### ISSUE TITLE
执行BBDown login的时候m1 报以下错误

### ISSUE THREAD

**Issue by ge2009** [codebude/QRCoder#356]
A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.

**Comment by codebude** [comment]
Can you give more details? Sorry, but this is not enough information to start analyzing your problem. 😞 

Note: I checked your main repository and saw that you target `net6.0`. So I can guess that you may have the same problems as described in #354 - at least if you run your app on any other platform than windows. But without more information this is only a guessing.

**Comment by codebude** [comment]
Hi @ge2009 ,

I made some changes, that possibly solve your issues. Can you please take the latest CI-build and check if it's working for you? [CI-Build Packages](https://github.com/codebude?tab=packages&repo_name=QRCoder)

If you need help on how to use Github Packages as NuGet package source, let me know (or check [this article](http://webcache.googleusercontent.com/search?q=cache:i_gL6oIwpr8J:www.catiawidgets.net/2021/04/20/creating-github-packages-and-accessing-them-in-nuget/+&cd=1&hl=de&ct=clnk&gl=de)).

**Comment by codebude** [comment]
Issue should be solved with the new QRCoder 1.4.3 release: https://www.nuget.org/packages/QRCoder/1.4.3
