### ISSUE TITLE
Error: QRCode does not contain a Constructor that takes 1 argument

### ISSUE THREAD

**Issue by sonisp** [codebude/QRCoder#360]
Hi,
I have downloaded and installed the Nuget Package QRCoder 1.4.2 and when I am trying to use the Constructor I am getting the below two bugs.

## Type of issue
**Bug 1:**  QRCode does not contain a Constructor that takes 1 argument . Attached reference **QRCode_Constructor_Bug.png**
**Bug 2:**  QRCode does not contain a definition for GetGraphic and no accessible method..etc. Attached reference **QRCode_GetGraphic_Bug.png**

## Steps to Reproduce (for bugs)
1. Install Nuget Pacakge QRCoder (ver 1.4.2) in Visual Studio Console App.
2. Copy code from GIT Sample 

## Your Environment
1. QRCoder (ver 1.4.2)
2. Visual Studio 2019
3. Console App . Net Framework 4.7.2
4.  Windows 10

<img width="593" alt="QRCode_Constructor_Bug" src="https://user-images.githubusercontent.com/10267246/145162250-dc07e4a8-ab07-4822-8962-18ec2bcc11ca.png">
<img width="926" alt="QRCode_GetGraphic_Bug" src="https://user-images.githubusercontent.com/10267246/145162261-385e2d06-18e1-435b-a991-bf5ffbd194d2.png">

**Comment by codebude** [comment]
Hi @sonisp ,

the errors look a little bit strange. Can you please show/post the part of your code with the `using`-statements? Have you added any other library, that contains a class named "QRCode"? 

I tried to reproduce the error and created a minimal project (VS2022, .NET4.7.2, QRCoder 1.4.2) with the following code and everything worked as expected:
```csharp
using QRCoder;
using System.Drawing;

namespace ConsoleAppQRCodeTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode("The text which should be encoded.", QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);

            System.Console.WriteLine("Successfully generated QR code.\nPress <any> key to end the program.");
            System.Console.ReadKey();
        }
    }
}
```

Feel free to download my test project and try it yourself. If it runs, there must be another error in your app:  [ConsoleAppQRCodeTest.zip](https://github.com/codebude/QRCoder/files/7677564/ConsoleAppQRCodeTest.zip)

**Comment by codebude** [comment]
Hi @sonisp ,

could you try out my sample project and if so, does it run on your environment?

**Comment by sonisp** [comment]
Hi @codebude, will try and revert. Ty

**Comment by codebude** [comment]
Since I haven't heard anything, I guess it worked out and will close the issue now. If you still have problems, let me know, then we can re-open the issue.

**Comment by jianliulin** [comment]
<TargetFramework>net6.0-windows</TargetFramework>  is ok

<TargetFramework>net6.0</TargetFramework>  is error

It may be caused here：
![image](https://user-images.githubusercontent.com/4531974/146126197-4a70bfb4-c320-4c09-8218-db2f4cb6bc61.png)

**Comment by codebude** [comment]
@jianliulin it can't work in net6.0... https://github.com/codebude/QRCoder/issues/361#issuecomment-992152570
