### ISSUE TITLE
QRCoder 1.4.3 not QRCode class

### ISSUE THREAD

**Issue by a645010545** [codebude/QRCoder#364]
## Type of issue
[√ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

## Expected Behavior

QRCodeGenerator generator = new QRCodeGenerator();
            QRCodeData codeData = generator.CreateQrCode(text, QRCodeGenerator.ECCLevel.M, true);
            QRCode qrcode = new QRCode(codeData);
            Bitmap qrImage = qrcode.GetGraphic(pixel, Color.Black, Color.White, true);
## Current Behavior

QRCodeGenerator generator = new QRCodeGenerator();
            QRCodeData codeData = generator.CreateQrCode(text, QRCodeGenerator.ECCLevel.M, true);
            QRCode qrcode = new QRCode(codeData);
            Bitmap qrImage = qrcode.GetGraphic(pixel, Color.Black, Color.White, true);
## Your Environment

In QRCoder 1.4.2 class QRCode is ok.QRCode qrcode = new QRCode(codeData); do not error
Burt In QRCoder 1.4.3 class QRCode is error.

**Comment by codebude** [comment]
Hi @a645010545 ,

this "issue" was already discussed in #361. Please read the discussion and my answer over there. If you then still have questions, let me know.

**Comment by a645010545** [comment]
> 嗨@a645010545，
> 
> 这个“问题”已经在[#361 中](https://github.com/codebude/QRCoder/issues/361)讨论过。请阅读那里的讨论和我的回答。如果您还有疑问，请告诉我。



> Hi @a645010545 ,
> 
> this "issue" was already discussed in #361. Please read the discussion and my answer over there. If you then still have questions, let me know.


> Hi @a645010545 ,
> 
> this "issue" was already discussed in #361. Please read the discussion and my answer over there. If you then still have questions, let me know.

Thanks
