### ISSUE TITLE
Compatibility for .NET 6

### ISSUE THREAD

**Issue by loebi-ch** [codebude/QRCoder#365]
Hi there!

After upgrading to .NET 6, type ```QRCode``` is not recognized anymore.

![image](https://user-images.githubusercontent.com/28792333/146945153-b9ea0721-ab26-4df8-b369-393730544417.png)

How can I get a ```System.Drawing.Bitmap``` from ```QRCodeData```?

I'm only using on Windows. My target framework is ```net-6.0```.

Best regards
Andy

**Comment by loebi-ch** [comment]
I answer this issue by myself.

I changed the target framework from ```net-6.0``` to ```net-6.0-windows```.

![image](https://user-images.githubusercontent.com/28792333/146948231-6fadc0f4-7461-4ff3-90ac-1199ef7da08b.png)

**Comment by WiseyD** [comment]
Changing the target framework wont get it to work. It will not display a QR code on .net6

**Comment by pccai** [comment]
pls use SkiaSharp.QrCode
