### ISSUE TITLE
2 questions 1.4.2 & 1.4.3 on ArtQRCode-Renderer

### ISSUE THREAD

**Issue by AlexandreZaytsev** [codebude/QRCoder#367]
Hi!
please take a look

ArtQRCode-Renderer (1.4.2 1.4.3)  [example of a call method](https://github.com/AlexandreZaytsev/QRCoderArt/blob/master/FormMain.cs#L698)
1.1
when using the drawQuietZones flag for finderPatternImage
true - without offset?
false - ok
![image](https://user-images.githubusercontent.com/16114000/147197716-783ffd17-9dca-432c-a2ee-3493d391a319.png)
![image](https://user-images.githubusercontent.com/16114000/147197745-dd9092c4-b207-4602-87cf-34bdfca4ff18.png)

1.2
pixel Size Factor didn't work for me - size (shape) 
 dots - does not change... what could be the matter?
![image](https://user-images.githubusercontent.com/16114000/147197763-b828117a-ec3c-41bc-83f6-114a24cc445a.png)

ps
[test app source](https://github.com/AlexandreZaytsev/QRCoderArt)

**Comment by AlexandreZaytsev** [comment]
comment on question 1.2 artmode
pixelsPerModule - 2 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148988099-80eef6f0-a304-4d66-bf97-92a917dbbf72.png)

pixelsPerModule - 3 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148988350-2b7ed4f8-8d19-4613-8dcb-85f982c9246c.png)

pixelsPerModule - 4 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148988492-c1f9896b-46c2-4a9c-be3d-97b784225cab.png)

pixelsPerModule - 5 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148988785-3629ddd8-55eb-461f-987a-2d9e9b41d934.png)

pixelsPerModule - 6 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148988998-1ee114b3-d47a-4179-9515-5884bb57fe89.png)

pixelsPerModule - 7 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148989198-4b843bec-6b85-42bc-b416-3f8d5e57f4b6.png)

pixelsPerModule - 8 pixelSizeFactor 0-1
![image](https://user-images.githubusercontent.com/16114000/148989354-1bc817b7-a1e3-49b6-ab0f-bd9fa479fbdf.png)

etc. - artifacts
the role of the pixelSizeFactor parameter is not clear

if the diameter of the point changed - then yes, otherwise it is not clear why

**Comment by codebude** [comment]
Both bugs mentioned were fixed in https://github.com/codebude/QRCoder/pull/408 and https://github.com/codebude/QRCoder/pull/474 and are part of the recently release QRCoder 1.5.0.
