### ISSUE TITLE
NuGet support

### ISSUE THREAD

**Issue by Philpax** [codebude/QRCoder#37]
Is it possible to put QRCoder on NuGet for ease of use/deployment?

**Comment by codebude** [comment]
Hello @Philpax ,

you can find the library via the following link on NuGet: [https://www.nuget.org/packages/QRCoder/](url)

Please notice that I've published it just a couple of minutes ago, so it may take some time until it appears via NuGet search.

Just for clarification:

- Each commit to the Github repo will automatically pushed to MyGet, build on their build servers and packaged to a NuGet package

- If it's a "stable" release, I will push the package from MyGet to NuGet.

If you're interested in the latest builds, feel free to grab the MyGet feed, which is round about 5 minutes behind each and every commit. Just add the MyGet feed as "package source" in Visual Studio "Tools->Options->NuGet Package Manager->Packet Sources".

NuGet V3 feed URL (Visual Studio 2015+) [https://www.myget.org/F/qrcoder/api/v3/index.json](url)
NuGet V2 feed URL (Visual Studio 2012+) [https://www.myget.org/F/qrcoder/api/v2](url)

**Comment by Philpax** [comment]
Fantastic, thank you very much!
