### ISSUE TITLE
Qrcode size is increased dramaticaly when improving quality

### ISSUE THREAD

**Issue by jwdsoft** [codebude/QRCoder#385]
I'm trying to use this library for generating QrCode for an application like this 
QRCodeGenerator qrgen = new QRCodeGenerator();
QRCodeData qrdata = qrgen.CreateQrCode(info, QRCodeGenerator.ECCLevel.Q);
QRCode qr = new QRCode(qrdata);
Bitmap bmp = qr.GetGraphic(7);
for me the bandwith and size is very important. when usign GetGraphic(7) the quality is good but the size of the QrCode is 750k although the data in he info variable is only 127 caracters long.
and if I use qr.GetGraphic(1);
the size is acceptable 15k but the image quality is nearly unscannable (I have to make the picture big to scan it get scanned successfuly only a few times)
when using online QrCode generators (this one for example (https://www.the-qrcode-generator.com/)) the generated image quality is very good and also lighweight :4k
I don't know why is that specialy for this very tiny piece of text.

## Type of issue
[x] Bug  
[] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by hbdbim** [comment]
The method you are using generates a bitmap image.
Try using the png example.
https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#25-pngbyteqrcode-renderer-in-detail

**Comment by jwdsoft** [comment]
Thank you so much that's much much better now.You're the best
