### ISSUE TITLE
Regex  apostrophe dosn't match with Adress

### ISSUE THREAD

**Issue by Seekny** [codebude/QRCoder#388]
Hello,

i found an issue when im trying to add a new Client with the method : SwissQrCode.Contact.WithStructuredAddress();

There is a Regex as define in the library like : **@"^([a-zA-Z0-9\.,;:'\ \+\-/\(\)?\*\[\]\{\}\\`´~ ]|[!""#%&<>÷=@_$£]|[àáâäçèéêëìíîïñòóôöùúûüýßÀÁÂÄÇÈÉÊËÌÍÎÏÒÓÔÖÙÚÛÜÑ])*$"** on the Street parameter.

When i had the follow string 'Route du Poirier à l’âne', i got the exception : 

"Name must match the following pattern as defined in pain.001: {charsetPattern}"

It appears that the apostrophe between the l & âne is not valid.

Is it possible to add this apostrophe : < ’ > ?

Sorry for bad english

**Comment by codebude** [comment]
This should be fixed by https://github.com/codebude/QRCoder/pull/432 which is part of the QRCoder 1.5.0 release.
