### ISSUE TITLE
it's required fields that should not exceed 300, not optional + required

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [codebude/QRCoder#392]
did you read https://sbqr.ru/standard/files/standart.pdf?

it's required fields that should not exceed 300, not optional + required
https://github.com/codebude/QRCoder/blob/cecf2066d3f3a74b142aaa7c8d9f744c4673118c/QRCoder/PayloadGenerator.cs#L2531

please fix asap

**Comment by ildar-shaymukhametov** [comment]
Guuuys, it must be done asap

**Comment by kinkeadian25** [comment]
So it just needs to be  if (bytesOut.Length >= 300)

**Comment by ildar-shaymukhametov** [comment]
no, the spec says: 
![image](https://user-images.githubusercontent.com/74532770/196644261-e53938fc-4aab-467e-8358-40808a16e319.png)
meaning only required fields should not exceed 300, meaning bytesOut should contain only required fields
it says nothing about optional fields

**Comment by ildar-shaymukhametov** [comment]
about optional fields:
the spec says: 
![image](https://user-images.githubusercontent.com/74532770/196645368-d2694720-0027-453d-b247-d615c1b535b3.png)
meaning what free space remains may be used by optional fields
