### ISSUE TITLE
QRCOder.SvgQRCode is not available for .net6 Web Application. SVG is mostly used in web applications and not really relevant for windows apps.. I just added the SvgQRCode code to my web application to continue but you may want to ensure you can create svg for web in your package.

### ISSUE THREAD

**Issue by endstreet** [codebude/QRCoder#395]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by coddo** [comment]
We're currently developing on Linux and deploying on Linux. Using `SvgQRCode` worked in version 1.4.1.
Now in version 1.4.3, the class `SvgQRCode` is no longer available. 

This looks to be a blocker for anyone developing for Linux and wanting to upgrade to .NET 6.

**Comment by PierreJeudiMerci** [comment]
The main reason seems to be the following breaking change from .Net 6 : https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by Shane32** [comment]
Fixed by:
- #490

**Comment by codebude** [comment]
As @Shane32 wrote - it's fixed. From QRCoder release 1.5.0 on the SvgQRCoder is avaible also on .NET 6+ (and newer) on non-Windows platforms.
