### ISSUE TITLE
How to create a QR with a small pixel size.

### ISSUE THREAD

**Issue by yuya-tani** [codebude/QRCoder#396]
Hi.
I always use QR Coder. Thank you.

Type of issue
[ ] Bug
[X] Question (e.g. about handling/usage)
[ ] Request for new feature/improvement

I want to make a QR with a fairly small size. (SVG mode)
Specifically, it is a QR with a cell size of 0.33 mm.

The "pixelsPerModule" parameter of the "GetGraphic" method is
It is int, and if you create a QR by setting the minimum value of 1,
The size of one cell was 0.35 mm.
Since it is an int, it is not possible to specify a decimal number smaller than 1, but is it possible to create a QR with a smaller size?

Best regard.

**Comment by Shane32** [comment]
The current version has a bug where `pixelSizeFactor` is ignored.  See PR #408 for the fix.

**Comment by Shane32** [comment]
Actually, that's for the dot size relative to the cell size.  It is true that you cannot set the cell size to a non-integer.  However, a SVG is scalable; you can always scale it without losing quality.

**Comment by codebude** [comment]
> However, a SVG is scalable; you can always scale it without losing quality.

That's all to be said. Changing the size really doesn't matter. There is nothing like a "smaller" SVG. The SVG file will noticeably change in filesize, no matter if the target size is 1mm or 20m as SVG is a vector format. If you want to show/render the SVG really small, just set the scale when rendering the SVG in your application/website. 

Check:
- https://css-tricks.com/scale-svg/
- https://stackoverflow.com/a/11877423/251719
