### ISSUE TITLE
Logo insert after QRCode unable to scan

### ISSUE THREAD

**Issue by supun151515** [codebude/QRCoder#397]
I have added a non-transparent Bitmap as a logo. Then I am not able to scan the QRCode. I guess, because of the center logo, some of the QRCode pixels are hidden.

Bitmap qrCodeImage = qrCode.GetGraphic(20, Color.Black, Color.White, (Bitmap)Bitmap.FromFile("C:\\myimage.png"));

[Here is the link for logo, QrCode with Logo and without logo]
(https://drive.google.com/drive/folders/120zZPzvk_A-64r3As_NIEpom3j5BuYli?usp=sharing)

Cheers,
Supun

**Comment by technos12** [comment]
You should increase the quality of the qrcode, to have more repetition of
the data in the code. This is going to help if you then hide some of it
with an image.
Good try.

**Comment by supun151515** [comment]
Hi,
Can you suggest a code for me for that?

**Comment by technos12** [comment]
To be able to set this parameter, you have to add before your line of code :

QRCodeGenerator qrGenerator = new QRCodeGenerator();
//This is where we set the ECCLevel
QRCodeData qrCodeData = qrGenerator.CreateQrCode("The text which should be encoded.", QRCodeGenerator.ECCLevel.Q);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(20, Color.Black, Color.White, (Bitmap)Bitmap.FromFile("C:\myimage.png"));

The ECCLevel can be set to 4 levels : 
public enum ECCLevel
        {
            /// <summary>
            /// 7% may be lost before recovery is not possible
            /// </summary>
            L,
            /// <summary>
            /// 15% may be lost before recovery is not possible
            /// </summary>
            M,
            /// <summary>
            /// 25% may be lost before recovery is not possible
            /// </summary>
            Q,
            /// <summary>
            /// 30% may be lost before recovery is not possible
            /// </summary>
            H
        }

Hope you have your solution to make it work now :)

**Comment by technos12** [comment]
Ok, I checked your image examples. I think the image is too big, especially too wide. In the examples you can find online, only a small square in the center is used for a logo, so try to reduce the size of the image, and it may work.
Technically, by putting your image wide like that, you are overlapping areas that are used to "find and decode" the qrcode, so the system is lost.
Hope you find your way with that.

**Comment by supun151515** [comment]
Hi,
Thanks for the reply. Let me try with smaller logo and see

**Comment by codebude** [comment]
Da es kein weiteres Feedback mehr gab, schließe ich das issue. Solltest du weitere Hilfe benötigen @supun151515 , gib einfach Bescheid und öffne den Issue wieder.

Wie bereits von @technos12 angemerkt ist das Logo einfach zu groß. Ein QRCode darf nur zu maximal X Prozent verdeckt sein, bis er nicht mehr gelesen werden kann. Das X in X Prozent kann, wie ebenfalls bereits erwähnt, durch das ECC (Fehlerkorrektur) Level bestimmt werden. Wenn man mit Logos arbeitet, sollte immer das größtmögliche ECC-Level, also H gewählt werden.

Ist der QRCode, wie in deinem Fall, dann immer noch nicht lesbar, muss das Logo verkleinert werden. Hierzu kann der Parameter `iconSizePercent` genutzt werden. (https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#parameter-table) Verringere den Parameter, um das Logo kleiner zeichnen zu lassen.
