### ISSUE TITLE
How to set chart size in QRCoder

### ISSUE THREAD

**Issue by ziyagokalp** [codebude/QRCoder#402]
Hi.
Help me please about qrcode chart size. How to set width and height in C#?

**Comment by codebude** [comment]
I guess with "chart size" you mean setting the QR code graphic to a fixed sized, correct? That question was raised already in the past and answered in detail. Please check the answers of:
- https://github.com/codebude/QRCoder/issues/151
- https://github.com/codebude/QRCoder/issues/131

If this doesn't answer your question, please re-open this issue and specify your question with more details.
