### ISSUE TITLE
Improve QRCode output sharpness

### ISSUE THREAD

**Issue by DanielHolland** [codebude/QRCoder#404]
Hi there, 

[ ] Bug  
[X] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement  

I am looking at using this package in place of calling Google's Chart API to generate QRCodes, the implementation I've followed uses the basic example in Wiki. What I see is that the image output of the library is noticeably blurred / pixelated when compared to the output from Google Chart. 

![Screenshot 2022-06-01 at 12 00 19](https://user-images.githubusercontent.com/30952472/171379659-90a77202-acbb-4d47-91ef-27324590d1b7.png)

What can I do to improve on the image sharpness?

```
var url = "https://github.com/codebude/QRCoder/issues/new";
QRCodeGenerator _qrCode = new QRCodeGenerator();
QRCodeData _qrCodeData = _qrCode.CreateQrCode(url, QRCodeGenerator.ECCLevel.L);
PngByteQRCode qrCode = new PngByteQRCode(_qrCodeData);
byte[] qrAsPngByteArray = qrCode.GetGraphic(20);
using(var ms = new MemoryStream(qrAsPngByteArray))
{
    testQRCode.Image = new Bitmap(ms);
}
```

* Version used:  1.4.3
* Compiled from source or NuGet package?:  Nuget
* Payload/Encoded text:  "https://github.com/codebude/QRCoder/issues/new"
* Used payload generator:  QRCodeGenerator
* Used ECC-level:  L
* Used renderer class:  PngByteQRCode
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .NET 4.7.2

**Comment by digitaldirk** [comment]
@DanielHolland  I believe you want to raise the pixelsPerModule value in this line: 
`byte[] qrAsPngByteArray = qrCode.GetGraphic(20);`

[Source from the Wiki](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#25-pngbyteqrcode-renderer-in-detail)
<html>
<body>


Parameter name | Type | Default | Description
-- | -- | -- | --
pixelsPerModule | int |   | The pixel size each b/w module is drawn


</body>
</html>
It will make the file size larger but will sharpen the image.

### Alternative
[SvgQRCode](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#26-svgqrcode-renderer-in-detail) This one is vector based so it can be resized without loss of quality but it may not fit your requirements.

**Comment by codebude** [comment]
Hi @DanielHolland the solution to your problem was perfectly summarized by @digitaldirk thus I'm closing the issue. In case you have any further questions just reopen the issue. :-)
