### ISSUE TITLE
SwissQrCode: Please add info to wiki to use forceUtf8:=true in CreateQrCode

### ISSUE THREAD

**Issue by Quantoniz0r** [codebude/QRCoder#405]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Request to change / add info on wiki
[https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#318-swissqrcode-iso-20022](https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#318-swissqrcode-iso-20022)

In the "How to use it - simple way" code snippet, please add true for the _forceUtf8_ parameter in the call _qrGenerator.CreateQrCode(..._

In the "Good to know" section, please add the info, that the _forceUtf8_ parameter should be set to true when using this payload generator, otherwise QR bills containing umlauts (ä / ö / ü) will be validated with errors, as UTF8 is mandatory as stated in the official documentation.

## Reason for request
If the parameter _forceUtf8_ is not set, umlauts (ä / ö / ü) are encoded in ISO-8859-1. The official QR bill validators will report this as wrong, as UTF-8 is mandatory.

**Comment by Quantoniz0r** [comment]
The funny thing is: all tested banking apps don't care about UTF-8 and process the QR bill just fine. As far as I know only the validator websites are complaining.

**Comment by codebude** [comment]
Thanks for your feedback. I updated the sample code in the Wiki entry and added an additional note on the necessity of the forceUtf8 parameter. 
https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#318-swissqrcode-iso-20022
