### ISSUE TITLE
Swiss QRCode: New character set are available on 18.November 2022

### ISSUE THREAD

**Issue by RamonaFrickCH** [codebude/QRCoder#431]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  
<b>Swiss QRCode: New charaterset is available on 18. November 2022</b>

## Expected Behavior

A customer reported that he cannot use his company name with degree characters in the QRCode information (Contact / Name) and gets the following error message:
Contact: Name must match the following pattern as defined in pain.001: ^([a-zA-Z0-9\.,;:'\ \+\-/\(\)?\*\[\]\{\}\\`´~ )

Now I wrote with Sixpayment about the problem and answer to me, that on 18.November are new character set are allowed.

Here the message:
_Guten Tag Frau Frick, 
Vielen Dank für Ihr e-Mail. 
Die restlichen Zeichen werden dann umgewandelt. 
Im folgenden [Dokument|[Swiss Payment Standards 2022 (six-group.com)](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.six-group.com%2Fdam%2Fdownload%2Fbanking-services%2Finterbank-clearing%2Fde%2Fstandardization%2Fiso%2Fswiss-recommendations%2Fimplementation-guidelines-ct-2022.pdf&data=05%7C01%7Cramona.frick%40axians-infoma.ch%7C804f2c05650d4c34e1f008dac23853f4%7Ccae7d06108f340dd80c33c0b8889224a%7C0%7C0%7C638035845201374630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AdVSipt6eZkmoYuTVcDRbr7yGNIEUJW5JGIU8s6cHdM%3D&reserved=0)] sind auch die Zeichen aufgeführt. Der Zeichensatz wird ab dem 18. November, verglichen mit der vorherigen Version, erweitert werden. 

Partner Support 

SIX 
Banking Services_

## Possible Solution (optional)

customize/update in class Contact the variable charsetPattern
![QRCodeCharsetPatter](https://user-images.githubusercontent.com/105198572/201060833-aa37c525-bf49-4847-b9c4-1951c7be8163.PNG)

## Steps to Reproduce (for bugs)

Insert in the adress the name with _YXZ°_
Contact WithStructuredAddress(**string name**, string zipCode, string city, string country, string street = null, string houseNumber = null);

**Comment by RamonaFrickCH** [comment]
**Fix Issue in PayloadGenerator**
Line989

var charsetPattern = @"^([a-zA-Z0-9\.,;:'\ \+\-/\(\)?\*\[\]\{\}\\`´~ ^|]|[!""#%&<>÷=@_$£¡¢¤¥¦§¨©ª«¬®¯°±²³µ¶·¸¹º»¼½¾¿×Ø]|[àáâäãåāăąçćĉċčďđèéêëēĕėęěĝğġģĥħìíîïĩīĭįıĳķĸĺļľŀłñńņňŉŋòóôöōŏőõŕŗřśŝşšţťŧùúûüũūŭůűųŵýÿŷźżžßÀÁÂÄÃÅĀĂĄÇĆĈĊČĎĐÈÉÊËĒĔĖĘĚĜĞĠĢĤĦÌÍÎÏĨĪĬĮİĲĴĵĶĹĻĽĿŁÑŃŅŇŊÒÓÔÖÕŌŎŐŔŖŘŚŜŞŠŢŤŦÙÚÛÜŨŪŬŮŰŲŴÝŶŸŹŻŽÆÐÞæðøþŒœſ])*$";

**Comment by codebude** [comment]
Fixed with PR #432 . Bugfix will be part of QRCoder 1.5.0. Thanks for your support @RamonaFrickCH
