### ISSUE TITLE
Base64QRCode Type load fail using .net 6

### ISSUE THREAD

**Issue by csutorasbalazs** [codebude/QRCoder#442]
## Type of issue
[ ] Bug  

## Expected Behavior
I have used the Base64QRCode type in a netstandard2.0 class lib with asp.net core app 3.1 successfully so far.

## Current Behavior
Just moved to asp.net 6 and can not instantiate Base64QRCode anymore.

## Steps to Reproduce (for bugs)
Just create a .net 6 project add a package reference 1.4.3 and the type Base64QRCode is simply not listed in the namespace.

## Your Environment
VS 2022 

* Version used:  1.4.3
* Compiled from source or NuGet package?:  nuget
* Used renderer class:  Base64QRCode
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .net 6

![image](https://user-images.githubusercontent.com/38753213/213766769-e9dab31f-c526-4b15-a641-96f78dc75499.png)

**Comment by Shane32** [comment]
Fixed by:
- #495

**Comment by codebude** [comment]
This is fixed with #495 and will be part of QRCoder 1.5.0.
