### ISSUE TITLE
some generated QRCode cannot be scanner read

### ISSUE THREAD

**Issue by wunianqing** [codebude/QRCoder#45]
data:0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345

ECClevel: M

and almost 25% can not be scanner read

**Comment by wunianqing** [comment]
I found the bug.
Change file QRCodeGenerator.cs, line 647 with:

for (int i = 0; i < messagePolynom.PolyItems.Count; i++)

and the bug fixed.

I don't no why. If I am wrong, please tell me.

**Comment by codebude** [comment]
Thanks for you support, but I have to re-check this twice in a silent minute...
I removed your solution in this commit: https://github.com/codebude/QRCoder/commit/0e3856698d990dd7c705e3685d9cb43dcd634f60 
Before that, my code looked like your solution, but generated some other errors. So it seems the truth is somewhere inbetween.

**Comment by codebude** [comment]
Fixed in https://github.com/codebude/QRCoder/commit/bafdd1fd03a16835f07bf8af9198439bca203494
