### ISSUE TITLE
Base64QRCode class seems to be missing from the latest build

### ISSUE THREAD

**Issue by artizani** [codebude/QRCoder#451]
Base64QRCode class seems to be missing from the Nuget package, is it depracated or new ?

same issue as this  https://github.com/codebude/QRCoder/issues/442

**Comment by artizani** [comment]
figured this is due to the breaking changes in net 6. Simply convert byte array to base64 natively and ignore this file

**Comment by codebude** [comment]
This is fixed with https://github.com/codebude/QRCoder/pull/495 and will be part of QRCoder 1.5.0.
