### ISSUE TITLE
When will the new version be released

### ISSUE THREAD

**Issue by yb12306** [codebude/QRCoder#453]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by yb12306** [comment]
When will the new version be released

**Comment by TravelDailyTeam** [comment]
Has the maintenance of this project ceased? The last update was several years ago. Could you recommend any good alternatives now? It needs to be fully compatible with .NET Core 6+ and Linux, thank you.

**Comment by samsar777** [comment]
Good question. This is a great library, but questions if it has been ceased. Any news on an update, especially to `System.Drawing` issue?

**Comment by codebude** [comment]
The/a new version was released yesterday. A patch release followed a couple of minutes ago. The new release contains a lot of bugfixes and new features: https://github.com/codebude/QRCoder/wiki/Release-notes
Hope you enjoy it!
