### ISSUE TITLE
"ER225410741DB-0" qrcode is wrong

### ISSUE THREAD

**Issue by chenghuaiyu** [codebude/QRCoder#46]
I generate a batch of qrcode image and decode by zxing, but some qrcode cannot be decoded such as the string "ER225410741DB-0" which encoded in version 2 and "H" ECCLevel.

**Comment by codebude** [comment]
Could you please try to set the *forceUtf8* parameter in the createQRCode method to **true** and tell me if this solves your problems.

**Comment by chenghuaiyu** [comment]
I've solved the problem. It's the bug in function CalculateECCWords(). the reason is the leading polyitem's coefficent is zero in some case, removing this item lead to the item count less than 
eccWords, then continue doing XORs cause the final leadTermSource's last exponent is less than 0, so the wrong ECCWords are returned. The simple solution is appending an zero coefficient item in last position when removing the leading zero coefficient item. following is the code snippet.
--------------------------------
            for (var i = 0; (leadTermSource.PolyItems.Count > 0 && leadTermSource.PolyItems[leadTermSource.PolyItems.Count-1].Exponent > 0); i++)
            {
                if (leadTermSource.PolyItems[0].Coefficient == 0)
                {   
                    leadTermSource.PolyItems.RemoveAt(0);
                    leadTermSource.PolyItems.Add(new PolynomItem(0, leadTermSource.PolyItems[leadTermSource.PolyItems.Count - 1].Exponent - 1));
                }
                else
                {
                    var resPoly = this.MultiplyGeneratorPolynomByLeadtermCoefficient(generatorPolynom, this.GetAlphaExpFromIntVal(leadTermSource.PolyItems[0].Coefficient), i);
                    resPoly = this.ConvertToDecNotation(resPoly);
                    resPoly = this.XORPolynoms(leadTermSource, resPoly);
                    leadTermSource = resPoly;
                }
            }

**Comment by codebude** [comment]
Reopened, so that I don't forget to implement and merge it.

**Comment by codebude** [comment]
Fixed in https://github.com/codebude/QRCoder/commit/bafdd1fd03a16835f07bf8af9198439bca203494
