### ISSUE TITLE
Module size (note pixelsPerModule)

### ISSUE THREAD

**Issue by M-t-t-h** [codebude/QRCoder#463]
## Type of issue
[ ] Bug  
[X ] Question (e.g. about handling/usage)  
[X ] Request for new feature/improvement  

## Expected Behavior

First, thanks for this code, it's  great work and already full of utilities.
About my question (future request if not possible :) ): 
I d'like to get "smaller module", like modure with white border.
I Tried a lot of parameters but pixelPerModule not answer to my probleme and looks have small impact

Si, is it possible to change de "square size" (module size) ?
I attach a image. Left : what QRCode do, right: what i d'like to do.

![qrcodeTicket](https://github.com/codebude/QRCoder/assets/8056358/ac49853f-db60-4e66-b232-4ba04f6d7247)
Thanks in advance !

## Your Environment

Latest nugget for c# code

**Comment by codebude** [comment]
From QRCoder version 1.5.0 on (soon to be released), you can use the `ArtQrCode` renderer (instead of QrCode) and its parameter `pixelSizeFactor` to get your expected results.
See also: https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#211-artqrcode-renderer-in-detail
