### ISSUE TITLE
Intelligent Mail, IM, postal barcode support?

### ISSUE THREAD

**Issue by coinzdude** [codebude/QRCoder#465]
Can QRCoder generate the USPS Intelligent Mail (USPS 4-State Customer Code) image?

Intelligent Mail, also known as IM, the 4-State Customer Barcode, is a postal barcode adopted by the United State Postal Service for sorting and tracking letters and flats.

An example image and some more information https://barcodeguide.seagullscientific.com/Content/Symbologies/USPS_4-State_Customer_Code.htm

![image](https://github.com/codebude/QRCoder/assets/58857646/56fdd6e2-5942-4587-ad72-44f207f82c37)

**Comment by coinzdude** [comment]
FWIW I found an old library here https://www.codeproject.com/Articles/20579/USPS-OneCode-Barcodes

**Comment by Shane32** [comment]
This library is specifically for encoding QR codes... did you want the IM data in a QR code format?  If so, can you provide a sample of what that would be and/or a specification reference?

**Comment by codebude** [comment]
> Can QRCoder generate the USPS Intelligent Mail (USPS 4-State Customer Code) image?

No, as the name states QRCoder can only create QR codes. Other barcode formats are not supported.
