### ISSUE TITLE
更新到1.4.3,SvgQRCode没有了

### ISSUE THREAD

**Issue by xtxk110** [codebude/QRCoder#469]
运行环境更新到NET7，升级Qrcoder到1.4.3，SvgQRCode没有了。有没有相关替代的类或实现方法

**Comment by doggy8088** [comment]
有的，請直接將 TargetFramework 從 `net7.0` 修改為 `net7.0-windows` 即可使用。

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.4.3" />
  </ItemGroup>

</Project>
```

唯一的缺點就是無法跨平台，僅能支持 Windows 平台。

**Comment by koaqiu** [comment]
你可以把源代码中的SvgQrCode.cs 复制到你的项目中
删除 SvgLogo 相关代码，然后再修改第一行的条件编译（或者直接删除），这样就能在net6 或者net7 运行了。
如果需要Logo支持的话，你需要用 自己重写一下 处理位图的相关代码。

**Comment by Shane32** [comment]
In English, the original issue was:

> Updated the runtime environment to .NET 7, upgraded Qrcoder to version 1.4.3, SvgQRCode is no longer available. Are there any alternative classes or implementation methods?

This has been solved by:
- #490

**Comment by codebude** [comment]
Fixed with #490. Will be part of QRCoder 1.5.0 release.
