### ISSUE TITLE
PayloadGenerator.WiFi.Authentication.WPA2 missing

### ISSUE THREAD

**Issue by doggy8088** [codebude/QRCoder#471]
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior

It's related to https://github.com/codebude/QRCoder/issues/164

I think `PayloadGenerator.WiFi.Authentication` enum should add `WPA2` into it.

## Current Behavior

The `PayloadGenerator.WiFi.Authentication` don't have a `WPA2` item.

## Possible Solution (optional)

Add `PayloadGenerator.WiFi.Authentication.WPA2`.

## Steps to Reproduce (for bugs)

I tested in my company's Wi-Fi environment. I can only join the Wi-Fi when using `WPA2`.

```txt
WIFI:T:WPA2;S:<ssid>;P:<password>;;
```

The `T:WPA` won't work.

## Your Environment

* Version used:  1.4.3
* Compiled from source or NuGet package?:  NuGet
* Payload/Encoded text:  `WIFI:T:WPA2;S:<ssid>;P:<password>;;`
* Used payload generator:  `PayloadGenerator.WiFi`
* Used ECC-level:  Q
* Used renderer class:  `PngByteQRCode`
* Environment (.NET 3.5, .NET 4.X, .NETCore, ...):  .NET 7

**Comment by doggy8088** [comment]
@codebude When will you release new version to the NuGet Gallery?

**Comment by codebude** [comment]
Hi @doggy8088 , 
Yes, I will. The change will be part of version 1.5.0, that I plan to release soon. (I like to merge some more PRs, before doing a new release.)
