### ISSUE TITLE
Can Create a QR  with shapes of my logo

### ISSUE THREAD

**Issue by della11** [codebude/QRCoder#473]
## Type of issue
[ ] Bug  
[X] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment]
Unfortunately this issue isn't clear. If it's about setting a logo on the QRCode, yes it's possible. The GetGraphic() method of many renderers takes an logo a parameter. If the question was not about logos on QrCodes I don't understand the question. :-(
