### ISSUE TITLE
QR Code complexity

### ISSUE THREAD

**Issue by fvdhaterd** [codebude/QRCoder#50]
Hello,

After updating from 1.2.0.0 to 1.2.1.0 the complexity of the QR codes generated is increased.

1.2.0.0:
![1 2 0 0 test](https://cloud.githubusercontent.com/assets/1670838/18467093/d2396c50-799e-11e6-8bcc-d19e25ebf88d.png)

1.2.1.0:
![1 2 1 0 test](https://cloud.githubusercontent.com/assets/1670838/18467105/e89b1eda-799e-11e6-8160-0e4d1f4e44ca.png)

Is there a way we can force the QR code to be less complex in the new version? We need to print the QR codes on small labels and we always try to use the less complex QR code. Now we cannot update unfortunately to the newest version of your great library.

Regards,

Frank

**Comment by codebude** [comment]
Hi @fvdhaterd ,

this was a small bug due to the changes for crossplatform compatibility. Now it's fixed in https://github.com/codebude/QRCoder/commit/add18052d57d11f7507848829ca2760b4058e242

New version (1.2.2) will raise up on NuGet in the next half hour.

**Comment by fvdhaterd** [comment]
Thank you very much for the fast update! Really appreciate it. Looks good again.

![1 2 2 0 test](https://cloud.githubusercontent.com/assets/1670838/18470256/0762be9c-79ac-11e6-9e64-83417c25ba51.png)

Regards,
Frank
