### ISSUE TITLE
SvgQRCode with logo and disable quitzones has a hole

### ISSUE THREAD

**Issue by TheBlubb14** [codebude/QRCoder#500]
## Type of issue
- [x] Bug  
- [ ] Question (e.g. about handling/usage)  
- [ ] Request for new feature/improvement  

## Expected Behavior
When generating a graphic with `SvgQRCode`, using a logo and disabling the quitezones. The logo is in the middle of the qr code and the qr code is intact.

## Current Behavior
There is a "hole" in the top left area of the qr code and the image overlaps pixels.
![grafik](https://github.com/codebude/QRCoder/assets/12298942/f7b65bfd-c947-4a73-a56e-db13ea94497a)

## Steps to Reproduce (for bugs)
I have setup a simple blazor web ui here: https://theblubb14.github.io/QrCoderBlazor/
Source code is available here: https://github.com/TheBlubb14/QrCoderBlazor/blob/main/QrCoderBlazor/App.razor
Sample logo you can download from here: https://avatars.githubusercontent.com/u/94650532

1. Download the above logo and select it in the ui for upload
2. Disable the checkbox quiet zones
3. Enter one letter in the input
4. Click the button generate

## Your Environment
* Version used: 1.4.3
* Compiled from source or NuGet package?: Use latest available nuget package and copied `SvgQRCode` from source as the new changes to add a logo are not yet available via nuget. I removed some constructors which where not compatible and removed the `#ifs` to make it run under .net 8
* Payload/Encoded text:  a
* Used ECC-level: M
* Used renderer class: SvgQRCode
* Environment: net8.0 blazor webassembly

**Comment by Shane32** [comment]
Looks like perhaps the SvgQRCode class was supposed to clear an area below the image, but the calculation is off - probably due to the quiet zones.

Can you reproduce the issue in a simple console application?  It would be most convenient if you could post a simple snippet of code that reproduces the effect along with attaching the image you are using for the logo.  Then it should be simple to fix.

**Comment by codebude** [comment]
Seems to be the IsBlockedByLogo function that doesn't take the quiet zones into consideration:
https://github.com/codebude/QRCoder/blob/master/QRCoder/SvgQRCode.cs#L213

@TheBlubb14 can you try to set fill background to false in the SvgLogo object and check if the "hole" is gone then?

By the way - you don't have to compile from source. The latest commits are available via the CI packages: https://github.com/codebude/qrcoder/packages

**Comment by TheBlubb14** [comment]
> Looks like perhaps the SvgQRCode class was supposed to clear an area below the image, but the calculation is off - probably due to the quiet zones.
> 
> Can you reproduce the issue in a simple console application? It would be most convenient if you could post a simple snippet of code that reproduces the effect along with attaching the image you are using for the logo. Then it should be simple to fix.

```cs
using QRCoder;

var base64Img = "iVBORw0KGgoAAAANSUhEUgAAADIAAAAyBAMAAADsEZWCAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAADUExURf8AABniCTcAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAUSURBVDjLYxgFo2AUjIJRAAUMDAAFFAABr92aEgAAAABJRU5ErkJggg==";
using var ms = new MemoryStream(Convert.FromBase64String(base64Img));
var qrCodeData = QRCodeGenerator.GenerateQrCode("a", QRCodeGenerator.ECCLevel.M);
var logo = new SvgQRCode.SvgLogo(new System.Drawing.Bitmap(ms));
var svg = new SvgQRCode(qrCodeData);
var rendered = svg.GetGraphic(24, "#000000", "#FFFFFF", false, SvgQRCode.SizingMode.ViewBoxAttribute, logo);
Console.WriteLine(rendered);
//File.WriteAllText("logo.svg", rendered);
```

**Comment by TheBlubb14** [comment]
> Seems to be the IsBlockedByLogo function that doesn't take the quiet zones into consideration: https://github.com/codebude/QRCoder/blob/master/QRCoder/SvgQRCode.cs#L213
> 
> @TheBlubb14 can you try to set fill background to false in the SvgLogo object and check if the "hole" is gone then?
> 
> By the way - you don't have to compile from source. The latest commits are available via the CI packages: https://github.com/codebude/qrcoder/packages

Setting `fillLogoBackground` to `false` resolves the issue. So there is an issue in the calculation i guess.

I cannot access your CI nuget packages from github as the packages link is not clickable. I believe that only people with write access to this repo can download the packages.

![grafik](https://github.com/codebude/QRCoder/assets/12298942/deb61c6c-bbeb-451a-8e9d-f72664ae3ee9)

**Comment by Shane32** [comment]
@TheBlubb14 GitHub Packages unfortunately requires authentication for both public and private repositories.  

See: https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages

**Comment by Shane32** [comment]
So to clarify, you have access -- it is public -- but you still need to use a GitHub PAT to authenticate.

**Comment by TheBlubb14** [comment]
> So to clarify, you have access -- it is public -- but you still need to use a GitHub PAT to authenticate.

Thanks now it is working with the CI packages.
I tried this before, but i only added my github registry, not the codebude one..

**Comment by codebude** [comment]
@TheBlubb14 Should be fixed with the latest build. If you still experience faulty behaviour feel free to re-open the issue

**Comment by TheBlubb14** [comment]
> @TheBlubb14 Should be fixed with the latest build. If you still experience faulty behaviour feel free to re-open the issue

Its fixed, thanks
