### ISSUE TITLE
svg transparency support?

### ISSUE THREAD

**Issue by johmarjac** [codebude/QRCoder#511]
does svg renderer support transparency ?

**Comment by codebude** [comment]
You can use rgba values (https://www.w3schools.com/cssref/tryit.php?filename=trycss_color_hexa) in the darkColorHex and lightColorHex parameters of the SvgQrCode constructor. But please be aware that not all applications can handle SVGs with transparency defined this way. So ensure upfront that your target application is able to render transparency.

**Comment by johmarjac** [comment]
> You can use rgba values (https://www.w3schools.com/cssref/tryit.php?filename=trycss_color_hexa) in the darkColorHex and lightColorHex parameters of the SvgQrCode constructor. But please be aware that not all applications can handle SVGs with transparency defined this way. So ensure upfront that your target application is able to render transparency.

Thanks i actually tried it before but ended up in only black rectangle. I must have made something wrong because now it works. I dont know why.

great library , keep up the good work 💪🏻
