### ISSUE TITLE
want to generate SVG file of 2.5cm which contain 2600Bytes of data to SCAN in QR any suggestion

### ISSUE THREAD

**Issue by lalwanikamaldev** [codebude/QRCoder#518]
## Type of issue

[ ] Question (e.g. about handling/usage)

**Comment by Shane32** [comment]
Sample code:

```cs

using QRCoder;
using System;
using System.IO;

class Program
{
    static void Main()
    {
        // Example content with 2600 characters (this will need to be replaced by your actual content)
        string content = new string('a', 2600); // Replace this with your desired content

        // Initialize the QR code generator with high error correction level to accommodate a large amount of data
        QRCodeGenerator qrGenerator = new QRCodeGenerator();
        QRCodeData qrCode = qrGenerator.CreateQrCode(content, QRCodeGenerator.ECCLevel.L);

        // Generate the QR code as an SVG
        SvgQRCode svgQrCode = new SvgQRCode(qrCode);
        string svgString = svgQrCode.GetGraphic(1);

        // Save to a file or use the string as needed
        File.WriteAllText("qr_code.svg", svgString);

        Console.WriteLine("QR Code generated and saved as SVG.");
    }
}
```

**Comment by codebude** [comment]
As @Shane32 has already correctly pointed out: It is technically possible to encode ~2600 bytes in a QR code and save it as SVG. However, this becomes illegibly small with a display size of 2.5cm x 2.5cm. 

I think here you will either have to distribute your user data over several codes or you store the data e.g. on a server and encode only the url to the data in a QR code.

I hope this answers your question. Let us know if there are any further questions or if we can close the issue.

**Comment by lalwanikamaldev** [comment]
@Shane32 i want qr contain all data offline

**Comment by codebude** [comment]
A reader can read it if the image provided has enough details. I guess your reader uses a camera? In that case you must upgrade your hardware/camera to capture the image of the QR code with enough details. Every block must be clearly visibile in the image captured that you pass to your reader.
