### ISSUE TITLE
Issue was in the last digit of QR Code. It was showing (. * - + and Sometimes X Y A B Z). The String is M*******7202 * is as Character.

### ISSUE THREAD

**Issue by AshishExo** [codebude/QRCoder#535]
## Type of issue
**Issue was in the last digit of QR Code. It was showing (. * - + and Sometimes X Y A B Z). The String is M*******7202 * is as Character.**  

How to solve this type issue??

QRCodeGenerator qrGenerator = new QRCodeGenerator();
        QRCodeGenerator.QRCode qrCode = qrGenerator.CreateQrCode(code, QRCodeGenerator.ECCLevel.Q);
        System.Web.UI.WebControls.Image imgBarCode = new System.Web.UI.WebControls.Image();
        imgBarCode.Height = 950;
        imgBarCode.Width = 950;
        using (Bitmap bitMap = qrCode.GetGraphic(20))
        {
            using (MemoryStream ms = new MemoryStream())
            {
                bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                byte[] byteImage = ms.ToArray();
                imgBarCode.ImageUrl = "data:image/png;base64," + Convert.ToBase64String(byteImage);
            }
            plBarCode.Controls.Add(imgBarCode);

        }

I am using the same code to generate the placard. 

<img width="104" alt="image" src="https://github.com/codebude/QRCoder/assets/54029205/8bb8cbe4-c551-42c1-a848-e97b4b45d4e9">

Using this version.

**Comment by codebude** [comment]
Tested with the current release and couldn't reproduce the error. @AshishExo please confirm, that the current release solves your problem. (You can grab the current version via Nuget: https://www.nuget.org/packages/QRCoder)

**Comment by codebude** [comment]
Closed issue due to lack of feedback. Feel free to re-open if the error still occurs with the latest release.
