### ISSUE TITLE
Install error QRcode 1.2.3

### ISSUE THREAD

**Issue by jev001ab** [codebude/QRCoder#57]
After installing: PM> Install-Package QRCoder
Error:
Install-Package : Could not install package 'QRCoder 1.2.3'. You are trying to install this package into a project that targets 'MDD,Version=v8.1', but the package does not contain any assembly references or cont
ent files that are compatible with that framework. For more information, contact the package author.

Do you have a new version with this version?

**Comment by codebude** [comment]
What is the target/type of your application where you want to use the QRCoder? (WinForms, WPF, Universal App/UWP, Windows Phone, Mono, ASP, ...?)

**Comment by codebude** [comment]
Hi @jev001ab ,

In this commit https://github.com/codebude/QRCoder/commit/84ea895fafb4e14a29cb44f7c421b0d27880e35f I reconfigured the target framework config. Version 1.2.4 includes these changes. Please test, if this solves your problem.

**Comment by codebude** [comment]
There was just another problem. Build scripts are fixed by https://github.com/codebude/QRCoder/pull/58 now. Within the next minutes QRCoder 1.2.5 will appear on Nuget. This release fixes your problems.
