### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by felixletsplayYT** [codebude/QRCoder#59]
Install-Package : The current environment doesn't have a solution open.
At line:1 char:1
+ Install-Package QRCoder
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by codebude** [comment]
Hi @felixletsplayYT  ,

this isn't a problem with the Nuget package, but with your Visual Studio project. Please try the following:

> In the package manager console, make sure to select the default project.
> If there are no choices, it means that there is no solution file created for your project. When I tested this, I was able to fix the problem by pressing Ctrl + Shift + S (Save all). Visual studio then prompted me to select a directory for my .sln file and NuGet then successfully recognized my solution/project.
> [Quote from: stackoverflow.com](http://stackoverflow.com/a/25714793/251719)

Please give a short feedback if this solved your problem.
