### ISSUE TITLE
Missing QRCoder.dll ?

### ISSUE THREAD

**Issue by MatteoMichelotti** [codebude/QRCoder#60]
Hello, I came across this repo and would like to use it, but I cannot seem to find the QRCoder.dll you mention in the readme file.
Am I completely blind, or am I doing something wrong? (Either is very possible)

Thanks :)

**Comment by codebude** [comment]
Hi @MatteoMichelotti ,

you're not blind, but this is wanted. On Github you'll only find the sourcecode. So you have three options now:

1. Download/Checkout the sourcecode from Github and compile the .dlls yourself
2. Install the Nuget-package into your Visual Studio project as described in the [readme](https://github.com/codebude/QRCoder/blob/master/readme.md)
3. Download the [Nuget-Package](https://www.nuget.org/api/v2/package/QRCoder/1.2.5), unzip it (for example with 7-zip) and take the .dlls
