### ISSUE TITLE
Add Logo to QR-Code

### ISSUE THREAD

**Issue by simonmau** [codebude/QRCoder#64]
Hi, 
is there a way to add a Logo to the QR Code?

Like http://goqr.me/_Resources/Persistent/c51e9cb94c6c3e953542c764bb97a0e1cf033ca3/qrcode-logo-design-starbucks.png

**Comment by codebude** [comment]
Hi Simon, 

the "QrCode"-class has already an overload which takes an Bitmap-object which will be printed on the QrCode.

`public Bitmap GetGraphic(int pixelsPerModule, Color darkColor, Color lightColor, Bitmap icon=null, int iconSizePercent=15, int iconBorderWidth = 6, bool drawQuietZones = true)`

By passing the Bitmap icon to the _GetGraphics_ method the icon will be printed. By changing the _iconSizePercent_ parameter you can set up how much percent of the QrCode image will be covered by the icon (Min=1, Max=100). Please keep in mind that the higher this value is, the harder it is for QrCode readers to read out the QrCoder's payload.

**Comment by iAmBipinPaul** [comment]
Hi !
I don't see any overload method for  `GetGraphic()`  , which will take icon as svg string and it  will generate SVG.
```

namespace QRCoder
{
    public class SvgQRCode : AbstractQRCode, IDisposable
    {
        public SvgQRCode();
        public SvgQRCode(QRCodeData data);

        public string GetGraphic(int pixelsPerModule);
        public string GetGraphic(int pixelsPerModule, Color darkColor, Color lightColor, bool drawQuietZones = true, SizingMode sizingMode = SizingMode.WidthHeightAttribute);
        public string GetGraphic(int pixelsPerModule, string darkColorHex, string lightColorHex, bool drawQuietZones = true, SizingMode sizingMode = SizingMode.WidthHeightAttribute);
        public string GetGraphic(Size viewBox, bool drawQuietZones = true, SizingMode sizingMode = SizingMode.WidthHeightAttribute);
        public string GetGraphic(Size viewBox, Color darkColor, Color lightColor, bool drawQuietZones = true, SizingMode sizingMode = SizingMode.WidthHeightAttribute);
        public string GetGraphic(Size viewBox, string darkColorHex, string lightColorHex, bool drawQuietZones = true, SizingMode sizingMode = SizingMode.WidthHeightAttribute);

        public enum SizingMode
        {
            WidthHeightAttribute = 0,
            ViewBoxAttribute = 1
        }
    }
}
```

**Comment by jackeychina** [comment]
Where i can add my logo in below code : 

                string code = "asdasd";
                QRCodeGenerator qrGenerator = new QRCodeGenerator();
                QRCodeData qrCodeData = qrGenerator.CreateQrCode(code, QRCodeGenerator.ECCLevel.Q);
                QRCode qrCode = new QRCode(qrCodeData);
                System.Web.UI.WebControls.Image imgBarCode = new System.Web.UI.WebControls.Image();
                imgBarCode.Height = 200;
                imgBarCode.Width = 200;
                using (Bitmap bitMap = qrCode.GetGraphic(20))
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        bitMap.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                        byte[] byteImage = ms.ToArray();
                        imgBarCode.ImageUrl = "data:image/png;base64," + Convert.ToBase64String(byteImage);
                    }
                    pbb.Controls.Add(imgBarCode);
                }

**Comment by iAmBipinPaul** [comment]
Hi @codebude ,
Thank you for you the info. I don't know about low level stuff for  QR code `(Image/SVG )` , I will try this when I will get free time and If it works will definitely send pull request.

**Comment by hermanthotan** [comment]
Hi @iAmBipinPaul 

Are you able to make similar to the starbucks qr code?
Can you share the code to produce that qr

**Comment by nazariizahoroda** [comment]
I've an issue. I added icon in png format to my QR and now  I can't scan it. What can be a problem?

**Comment by nzhuravel** [comment]
Documentation says the image overload is present in Base64 renderer:
https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#23-base64qrcode-renderer-in-detail
But in reality (v1.6.0) it is not there. Is it a typo in docs?

Update: https://github.com/codebude/QRCoder/blob/master/QRCoder/Base64QRCode.cs#L121
Looks like the necessary constructor is disabled for .NET6 and later. Sad.
