### ISSUE TITLE
Issue in QR Image

### ISSUE THREAD

**Issue by nadeekapf1** [codebude/QRCoder#67]
I need to generate QR Image for below code. But QR Coder does not create correct image for it. Can I know a way to do it. it works for other codes well.

www.bethelonline.cn/certificate/PTGJQ9Q6

**Comment by codebude** [comment]
Hi @nadeekapf1 ,

could you please specify what exactly you want to encode (=payload) as QrCode? The url you posted? Contents of the website the url links to?

**Comment by nadeekapf1** [comment]
HI Raffael,

below is the exact text (code) which needs to be converted to a QRImage.

www.bethelonline.cn/certificate/PTGJQ9Q6

*Thanks & Regards*
*Nadeeka Fernando*

**Comment by nadeekapf1** [comment]
HI raffael,

I have an issue with this code also.
www.bethelonline.cn/certificate/Z4Z7MOYH

**Comment by codebude** [comment]
I created the following for QR codes (they differ in the ECC levels) for your payload. The QR codes are generated with the latest QrCoder version and I'm unable to see any error.

http://fs5.directupload.net/images/170419/7biaznjk.jpg
http://fs5.directupload.net/images/170419/tjxbbghs.jpg
http://fs5.directupload.net/images/170419/2572yfkv.jpg
http://fs5.directupload.net/images/170419/8ztdgyem.jpg

**Comment by nadeekapf1** [comment]
Hi,
Yes I was using a previous version. (https://www.aspsnippets.com/Articles/Dynamically-generate-and-display-QR-code-Image-in-ASPNet.aspx)

Now I updated from Nuget Package. It's working now. Thanks for helping us to find the issue

**Comment by Hydroque** [comment]
Is this tutorial valid still? If not, a take-down request/modification should be made.

**Comment by codebude** [comment]
I already wrote the author, and requested to update the tutorial and in best case remove the binaries and provide a Nuget link instead. Let's what happens.
