### ISSUE TITLE
Does not run on netstandard / core on Ubuntu

### ISSUE THREAD

**Issue by ByronAP** [codebude/QRCoder#69]
System.Drawing.KnownColors and other exceptions are thrown when running on Ubuntu using basic qr generation.

`public static Bitmap WriteQRImage(string data, int ppm = 20)
        {
            using (var qrGenerator = new QRCodeGenerator())
            {
                using (var qrCodeData = qrGenerator.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q))
                {
                    using (var qrCode = new QRCode(qrCodeData))
                        return qrCode.GetGraphic(ppm);
                }
            }
        }`

**Comment by ByronAP** [comment]
oddly enough i don't see KnownColors anywhere in the src.... hhhmmmmmm

**Comment by codebude** [comment]
I'll setup a test environment right now. Just to get as close as possible to your setup. What are you using? I assume...
- MonoDevelop
- Mono or which Framework?

**Comment by ByronAP** [comment]
Project is built using VS 17 on windows and published for Ubuntu
Runtime: .net core latest on Ubuntu 16

**Comment by ByronAP** [comment]
i haven't dug too deep yet but it looks like the issue is in the drawing library

**Comment by ByronAP** [comment]
The type initializer for 'System.Drawing.KnownColors' threw an exception

**Comment by ByronAP** [comment]
works fine on windows but fails on Ubuntu

**Comment by ByronAP** [comment]
and the library is ZKWeb.Fork.QRCoder 1.2.6 NuGet

**Comment by codebude** [comment]
Ok, I'll try that later. Right now I installed MonoDevelop on Kubuntu, created a new Gtk project, added QrCoder via Nuget and successfully compiled. 

I'll try the VS17 way later. And tell you if I had success.

By the way: There is an edit button, you don't have to make a new post for every sentence. ;-)

**Comment by ByronAP** [comment]
Thinks it is on windows and looks for gdi when under linux

**Comment by codebude** [comment]
This one drives me nuts. I downloaded your files, but wasn't able to open the .csproj in my Visual Studio (2015). So I guessed what you did and created a new VS2015 .NETStandard console project. After that I added you code and added a runtime (win10-x64) to the project.json file. Via "debug" button in VS I can start a console program with your code which runs.

And now the "trouble" part...

Then I added "ubuntu.16.10-x64" to the runtime list. But then dotnet restore failed. With "ubuntu.14.04-x64" it worked. Nevertheless I wasn't able to run the app nor get it compiled...

1. How to compile/export it for ubuntu? 
2. Do you use Visual Studio functions, the "dotnet" commandline or another way? 
3. Do you compile the program for Ubuntu on your Windows system or under Ubuntu?
4. And how to you start the program under ubuntu? Via terminal "dotnet QrDebugger.exe" or in another way?

Sorry for the questions, but until now I didn't need the netcore (preferring Mono/.NET (full) Framework). So right now the netcore stuff confuses me...

**Comment by ByronAP** [comment]
use VS 2017

**Comment by codebude** [comment]
Ok, then I'll you have to wait until the weekend. Because I won't install VS2017 and VS2015 side by side and have to setup a virtual machine first...

**Comment by codebude** [comment]
Ok, I managed to compile it on Ubuntu and ran into an error, which looks like the error you complained about.

``` 
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.GDIPlus.RunningOnWindows()
   at System.Drawing.KnownColors..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.KnownColors.FromKnownColor(KnownColor kc)
   at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule)
   at QrNetCore.Program.WriteQRImage(String data, Int32 ppm) in /home/raffael/MonoProjects/QrCoderNetcore/QrNetCore/Program.cs:line 23
   at QrNetCore.Program.Main(String[] args) in /home/raffael/MonoProjects/QrCoderNetcore/QrNetCore/Program.cs:line 10
```
It seems like a general error with the System.Drawing library. Another netcore System.Drawing lib had also similiar problems:
https://github.com/CoreCompat/CoreCompat/issues/3

Just to ensure that it is not the QrCoder but the Drawing lib, I made a retest by removing the Drawing reference and changed the QrCode type to "Abstract":

```
using QRCoder;
using System;

namespace QrNetCore
{
    class Program
    {
        static void Main(string[] args)
        {
            var img = WriteQRImage("SomeDataToQR");
            for (int i = 0; i< 80; i++){ Console.Write(img[i]);}
            Console.ReadKey();
        }

        // ReSharper disable once InconsistentNaming
        public static byte[] WriteQRImage(string data, int ppm = 20)
        {
            using (var qrGenerator = new QRCodeGenerator())
            {
                using (var qrCodeData = qrGenerator.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q))
                {
                    using (var qrCode = new BitmapByteQRCode(qrCodeData))
                        return qrCode.GetGraphic(ppm);
                }
            }
        }
    }
}
```

This one compiles and runs without problems. So you have three options:

1. Remove the System.Drawing reference and use BitmapByteQrCode. It contains a Bitmap file as byte[]. You can dump it to the harddisk as image or encode it as Base64 or ...
2. Fix the "missing libgdiplus" problem on your computer
3. Open an issue in the [ZKWeb System.Drawing repository](https://github.com/zkweb-framework/ZKWeb.System.Drawing) concerning the libgdiplus problem. (If you do so, feel free to link the issue to this one.)

**Comment by codebude** [comment]
Just for reference: Seems to be solved in this issue --> https://github.com/zkweb-framework/ZKWeb.System.Drawing/issues/7#issuecomment-299074196
