### ISSUE TITLE
Wireless SSID and Password Generation

### ISSUE THREAD

**Issue by ondrovic** [codebude/QRCoder#7]
Thanks for the great library, is there a way this could be used to generate Wireless Password QRCodes? I know you can pipe this through 

    WIFI:S:<SSID>;T:<WPA|WEP|>;P:<password>;;

 and it seems to work.

**Comment by codebude** [comment]
If you know that this pattern works, what exactly is the problem? You're able to pass any string to the generate-function, so even your WiFi pattern should work. Or did you ask for a special function, where you can pass the WiFi name and password, which then generates the pattern and the QR code automatically?

**Comment by ondrovic** [comment]
That would be a cool addition to have the function built, works fine as is though

**Comment by codebude** [comment]
Have a look at the "dev"-branch (https://github.com/codebude/QRCoder/tree/dev). There's a PayloadGenerator.cs now, which enables you to create this WiFi payloads. I'll just want to add some more payload types, before I merge the changes to the master-branch.
