### ISSUE TITLE
Does it Creates AddressBook or vcards?

### ISSUE THREAD

**Issue by jfshimul** [codebude/QRCoder#70]
what is the method of creating vcards or adress book?

**Comment by codebude** [comment]
Right now there is now vCard payload type. But feel free to contribute.

**Comment by codebude** [comment]
Hi @jfshimul 
with the last commit (https://github.com/codebude/QRCoder/commit/cc2add4c2f8b2d4e9909c70560f9d45d36663ad5) I added a *simple* ContactData payload generator. It supports: MeCard, vCard 2.1, vCard 3.0 and vCard 4.0.

For now it's just available via GitHub and not on NuGet. Next NuGet release will follow next week. If you need it earlier, use the [Nightly NuGet feed](https://github.com/codebude/QRCoder/wiki/How-to-use-QRCoder#installation) or copy code from GitHub.
