### ISSUE TITLE
not decode?

### ISSUE THREAD

**Issue by shumtn** [codebude/QRCoder#71]
This component is pretty good.
But there is a lack of important functions (not decoded)

**Comment by codebude** [comment]
Whatb do you man by "not decoded"? Do you mean that the library can only encode/create QR codes but can't read them?

**Comment by shumtn** [comment]
Yes, after reading the QR image, then parse to get the URL or number...

**Comment by codebude** [comment]
Hi @shumtn  - this library was planned as encoder, not as decoder. So right now there aren't any plans to implement a decoding component. But if you have the passion, feel free to contribute the decoding code part. ;-)

**Comment by Hydroque** [comment]
I was about to state that going through the code once more to refresh myself. I think the 'coder' part doesn't fit the objective of the library until the decoder comes into place. Stops people for mis-expecting.

**Comment by codebude** [comment]
Phew, maybe QrEncoder.NET would have been a better choice, when creating this project, but in my eyes it's too late for a change. A rename would give more confusion than it would help.

In addition to that I think that most people will read the "readme.md" before installing the package and then will realize that it's only encoder.

But as already told - if some of you is able to write the decoder part from bottom up, feel free to do so and send a pull request.

**Comment by zdarovka** [comment]
It is definitely a little problem (I did not read readme, my bad) and after implementing encoding, I started to look how to do decoding which is not available :-(

**Comment by codebude** [comment]
Hi @zdarovka ,

at first you're welcome. Feel free to write the encoder part and submit it via Pull Request. :1st_place_medal:

**Comment by tilkinsc** [comment]
Pretty sure you just use the library to reverse the saving process into the data structures then convert the blocks into data by reversing the to-block algorithm. Sounds simple, but I am not proficient in C# nor QR codes. Really I just follow to aid in helping.
