### ISSUE TITLE
Merge HOTP and TOTP algorithms into this library?

### ISSUE THREAD

**Issue by tilkinsc** [codebude/QRCoder#72]
Would be a neat addition. I have made several.

For people using TOTP in C#, it would go a lot more smoothly than importing yet another library. It is small and simple and I could do it.

Thoughts?

**Comment by codebude** [comment]
Hi @Hydroque ,

thanks for you offer and I really appreciate it. But before doing work which has already been done, have a look at the OneTimePassword payload generator:
https://github.com/codebude/QRCoder/blob/master/QRCoder/PayloadGenerator.cs#L1472
There is already a HOTP/TOTP implementation. If you idea/implementation is different, feel free to contribute. :-)

**Comment by Hydroque** [comment]
Yes, I understand what you have. Apart from URLs, you have the actual data.
https://github.com/Hydroque/LuaOTP

**Comment by codebude** [comment]
Ok, you meant not only the payload's structure, but the contents. So you meant to deliver a HOTP/TOTP generator. Feel free to write one and send a merge request.

**Comment by Sebazzz** [comment]
I would vote against it. It is out of scope for this library. This library focuses on generating QR codes and encoding data for those QR codes. Generating TFA codes themselves is a seperate responsibility and should belong in a seperate library.

**Comment by Hydroque** [comment]
It is so widely used that it doesn't matter.
