### ISSUE TITLE
SwissQrCode Currency is number instead CHF/EUR

### ISSUE THREAD

**Issue by stuzzicadenti** [codebude/QRCoder#74]
Hallo Raffi

Vielen Dank für die Implementierung der QR lib.

I've used the PayloadGenerator for the SwissQrCode and it uses a number (i.e. 756) instead of CHF.
Shouldn't it be CHF/EUR as specified in https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf page 20 Elementname Ccy?

Danke
Dani

**Comment by codebude** [comment]
Hi Dani,

thanks for your support. I fixed this bug with the following commit:
https://github.com/codebude/QRCoder/commit/6faad8520988be7e05555de89b92179456a5d233

New version will be released to NuGet in the next couple of minutes.
