### ISSUE TITLE
Please support drawQuietZones=false on BitmapByteQRCode

### ISSUE THREAD

**Issue by leopignataro** [codebude/QRCoder#78]
Dear QRCoder team,

Is there any impediment for supporting the `drawQuietZones = false` option on `BitmapByteQRCode`? If not, would you please be so kind as to consider adding it?

Thank you very much!

*PS: I know that option is available on the `QRCode` renderer, but I'm on .NET Core*

**Comment by codebude** [comment]
Hi @leopignataro ,

I added this task to my to-do list. Unfortunately I'm running a little out of time. So if anybody is faster, feel free to fork, edit and send in a pull request.

**Comment by leopignataro** [comment]
Thanks, @codebude !

We actually don't need it right away, our project currently runs on .NET Framework and is being ported to .NET Core, we'll only need it down the road, so we're happy to wait. Just knowing you're willing to eventually do it already enables us to use it right now on .NET Framework (we are being careful not to introduce new features to the product that will create problems in the port to .NET Core that is ongoing in parallel).

Thanks again!
