### ISSUE TITLE
Avoid adding dependency to UnityEngine if UnityQRCode is not used

### ISSUE THREAD

**Issue by dmirmilshteyn** [codebude/QRCoder#82]
I'm using the updated csproj format and the nuget package (PackageReference fields), and it ends up pulling in the UnityEngine dll, likely due to the transitive dependencies feature of the updated project format. I'm not using UnityQRCode at all, or anything related to Unity. Can this dependency be made more optional by moving it into a separate assembly/package?

**Comment by codebude** [comment]
Hi Daniel, 

when you don't need/want to use the Unity parts, then just...

- remove Unity from the project references
- delete the "UnityQRCode.cs" file in QRCoder folder
