### ISSUE TITLE
Unreabable QR Generation?

### ISSUE THREAD

**Issue by Jrud** [codebude/QRCoder#83]
![differentqr](https://user-images.githubusercontent.com/11812997/29746270-6dcd0412-8a9a-11e7-8b7e-24c8acac31dc.png)

![differentqroriginal](https://user-images.githubusercontent.com/11812997/29746285-af019952-8a9a-11e7-8a59-f74223813c11.png)

I created this QR barcode while testing given the code 044600016566 to encode.  It produced the attached barcodes that my 2D barcode scanner won't read.  I've generated numerous other barcodes with your DLL and they all read just fine except for this one.  The only difference that I can see is that the bottom right reference marker doesn't have a solid black border around the white square.

Is this a failure of the QR code generator, a failure of my scanner for not being able to detect something that is standard, or a failure of my understanding of how they work?

**Comment by codebude** [comment]
Hi John,
this doesn't look good. My scanner app isn't able to read this, too. Could please give more information on the encoding level used and the version of the QrCoder.dll?

**Comment by codebude** [comment]
Ok, I just generated your payload (044600016566) with all error levels and none of the QR codes looked like yours. Either you use an outdated version of the QrCoder or your input string wasn't "044600016566". ;-)

That's the code, which is generated for ECC Level "H", with the current library version:
![2017-08-27 13_58_19-qrcoder](https://user-images.githubusercontent.com/2236234/29749586-23e8e032-8b30-11e7-9900-3c2e7afbf08f.png)

**Comment by Jrud** [comment]
Here is the code I wrote to :

public static Bitmap MakeQR(string Text)
        {
            Bitmap Result = null;

            using (QRCoder.QRCodeGenerator Generator = new QRCodeGenerator())
            {
                using (QRCodeData Data = Generator.CreateQrCode(Text, QRCodeGenerator.ECCLevel.H))
                {
                    using (QRCoder.BitmapByteQRCode bbqc = new BitmapByteQRCode(Data))
                    { 
                        byte[] graphic = bbqc.GetGraphic(4);
                        
                        using (MemoryStream ms = new MemoryStream(graphic))
                        {
                             Result = new Bitmap(ms);
                        }
                    }
                }
            }

            return Result;
        }

I am using DLL version 1.3.0.0 

Are these incorrect?

**Comment by codebude** [comment]
Ok, you are using the BitmapByteQRCode. I re-checked, but I get the exact same image like shown in my screenshot before.
You got the DLL 1.3.0.0 from checking out and compiling the current Github code? If so, we should have the exact same code. I really don't get it, why my QR code looks different from yours.
a) Could you check the QR code result, when using the QRCoderDemo project/app from this Github repo?
b) Can you re-check (maybe via breakpoint/debugger) what your string (to be encoded) looks like. The only explanation for the difference, I can think of, is that your payload string isn't "044600016566".

**Comment by Jrud** [comment]
Ah, you were right, this was never a problem with the QR generator, I was passing in an empty string into the function from a bug farther up the process, and generating a QR with a blank for text seems to be what produces the non functional barcode.  Sorry to have annoyed you, mysoftware should never need to create a blank barcode so this is not an issue for me haha.

Thanks for the awesome tool!

**Comment by Hydroque** [comment]
Should QRCoder throw an error on an invalid input?

**Comment by codebude** [comment]
@Jrud - nice to hear, that you could solve your problems and thanks for the compliments.
@Hydroque - I think it's not QRCoder's task to catch empty payload. The QR standard (ISO18004) just talsk about maximum payload length, but not about minimum length. I couldn't find any hint in the ISO docs, which says that there must be at least one char of payload. In addition QR codes work also without payload and are still readable. So why should I prohibit something which is compliant to the norm? In my opinion, if this is unwanted, this should be handled by the applications (user) input validation.

**Comment by Hydroque** [comment]
Wasn't the point that the empty payload generated an invalid QR code though?

**Comment by codebude** [comment]
@Hydroque that's what @Jrud wrote, but not what he meant. He meant, that the QR code gave an unexpected result (=empty string). Technically the QR code was correct/working. And as I already explained, an empty QR code is valid by standard. So if one dosn't want his app to create empty QR coders that should be part of user input validation in GUI, not a part of library.
