### ISSUE TITLE
QRCode is not found

### ISSUE THREAD

**Issue by futurify-tanhoang** [codebude/QRCoder#84]
Hi,
I have just get your latest version (1.2.9) on nuget, then try the following codes:

`QRCodeGenerator qrGenerator = new QRCodeGenerator();
QRCodeData qrCodeData = qrGenerator.CreateQrCode("The text which should be encoded.", QRCodeGenerator.ECCLevel.Q);
QRCode qrCode = new QRCode(qrCodeData);
Bitmap qrCodeImage = qrCode.GetGraphic(20);`

There are no reference to QRCode. Do you look into this issue? Thanks!

**Comment by codebude** [comment]
Hi @futurify-tanhoang,

the code given by you is the standard sample code from our project. If this would produce an error, we hadn't published the library. So the error must be in your project/project configuration.

- Which target platform do you use (.NET 3.5, .NET 4.0, .NET Standard, ...)
- What is the **exact** error text you see?
- What files/libs are referenced in the "References"-folder of your project?

**Comment by codebude** [comment]
Hi @futurify-tanhoang did you solve your problem or you need any further help? If so, can you answer my questions from the comment above?

**Comment by codebude** [comment]
Since error can't be reproduced and thread-opener didn't answer --> closed. (Can be re-opened, if issue-opener answers.)
