### ISSUE TITLE
NuGet installation VS 2013 Intellisense issue

### ISSUE THREAD

**Issue by enshadowed** [codebude/QRCoder#88]
Greetings fellow GitHubbers,

Is anyone facing issues with intellisense when they install QRCoder through the in-VS NuGet Management? When i install it from there, intellisense stops working and also errors don't show up.

Kind Regards,
**enshadowed_**

**Comment by codebude** [comment]
Hi @enshadowed ,

I just created a new empty (C# WinForms-)project in VS2017 and added the NuGet package. Works without problems.

But I had a some problem (also in other projects) where Intellisense stopped working. In those cases it help to restart Visual Studio most times. If this doesn't work for you, please let me know, which version of Visual Studio you use and which kind of project (WinForms, WPF, UAT, ...) you used.

**Comment by enshadowed** [comment]
Dear Mr. @codebude,

First of all, thank you for creating this amazing project so we can stop scratching our heads with other builds out there that take ages of documentation to achieve something you do fast and simple. It appeared not to work with reloading. I had to clear obj/bin and rebuild the sln to get it fixed.

Thanks for your timed reply! It is much appreciated. 

Sincerely,
**enshadowed_**

**Comment by codebude** [comment]
Thanks for the kind feedback and glad to hear that you could solve your problems. :+1:
