### ISSUE TITLE
QrCodeGenerator: forceUtf8 results in invalid numeric codes

### ISSUE THREAD

**Issue by pontusi** [codebude/QRCoder#89]
If you pass forceUtf8: true but the text only contains numeric data then an invalid QR code is generated.

```C#
public static void Main(string[] args)
{
	var generator = new QRCodeGenerator();

	var validCode = new QRCode(generator.CreateQrCode("123456", QRCodeGenerator.ECCLevel.Q, forceUtf8: false));
	validCode.GetGraphic(10).Save("valid.png", ImageFormat.Png);

	var invalidCode = new QRCode(generator.CreateQrCode("123456", QRCodeGenerator.ECCLevel.Q, forceUtf8: true));
	invalidCode.GetGraphic(10).Save("invalid.png", ImageFormat.Png);
}
```

I suspect this is because PlainTextToBinary looks first at EncodingMode (which is Numeric in this case?) and GetDataLength looks first at forceUtf8.

**Comment by codebude** [comment]
Hi pontusi, 

thanks for the feedback and your analysis. You're right, when forceUtf8 was true, the QRCoder didn't check if the content is text content. Now byte-mode payload-encoding is forced, when forceUtf8 is set to true. https://github.com/codebude/QRCoder/commit/bd284c57552f177b961733611baf031aafb2f759

(Update of the NuGet package will follow in a couple of minutes.)
