### ISSUE TITLE
UnityEngine dependency

### ISSUE THREAD

**Issue by Symbai** [codebude/QRCoder#95]
In the readme it says it has no depedencies but in the nuget package there is a UnityEngine.dll inside the .NET4 folder which gets copied to output directory on every compile. Could you update the readme or offer a dependency-less version?

**Comment by codebude** [comment]
The Unity.dll is optional. You only need it, if you use the UnityQRCode-class. If not, just drop it, when deploying your application.

**Comment by Symbai** [comment]
While it's optional and I can delete it myself and the code works without, the reference still exist and this will cause potential problems. For example if the user has installed a similar DLL with different version into GAC, then your application will throw an exception even if it's not used by code.

That's why deleting referenced assemblies from output folder is a really bad idea, even if it works 90% of the time.

**Comment by sbrickey** [comment]
I would put forth that the correct answer is to have a separate QRCoder.Unity project/assembly. I myself want to minimize risk entirely, and thus removed both UnityEngine.DLL as well as UnityQrCode.CS.

Whether you have a separate project with the extra file (similar to the various CLR projects), or a sister project (references both QrCoder base as well as UnityEngine) with the UnityQrCode implementation... makes no diff to me

**Comment by ellisnet** [comment]
Another problem with UnityEngine.dll - from what I can see - is that it is unversioned and has no information (via right-clicking on it and choosing Properties) about where it came from, what license it has, or even really what it is.  So, it could get included in a distribution of an application - including a commercial software application - with no information about whether it is licensed code or not; if a person didn't know to delete it.  I am +1 on deleting it from the main QRCoder package; and including it in a separate QRCoder.Unity Nuget package.
Jeremy

**Comment by hotstone** [comment]
I've ended up here after discovering that UnityEngine.dll is suddenly being included in our deployment package.  As @ellisnet said, the UnityEngine.dll is unversioned and doesn't seem to be open sourced; I definitely think this functionality should be a separate optionally-installed package.

**Comment by codebude** [comment]
At first: sorry guys for the late response. But this is done now. I removed the UnityQRCode.cs/UnityEngine.dll from the main QRCoder project. From release 1.3.4 on this dependency is gone.

In addition to that I created [QRCoder.Unity](https://github.com/codebude/QRCoder.Unity) which contains only the UnityQRCode.cs + NuGet dependencies to the QRCoder and the UnityEngine. I also updated the readme.md and the [Wiki](https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#27-unityqrcode-renderer-in-detail).

I hope this solution fit your needs. Feel free to re-open the issue, if there's anything wrong with this solution or anything you like to discuss about.
